// <autogenerated />
using Microsoft.AspNetCore.Components;
using Microsoft.JSInterop;
using SpiderHood.Models;
using SpiderHood.Services;
using System.Globalization;

namespace SpiderHood.Components.Pages
{
    public partial class Home
    {
        private Guid IdBuilding = Guid.Empty;

        // Formatea siempre en la moneda configurada del edificio actual (BuildingConfiguration.Currency),
        // no en la del server -- ver CuotaExtensions.FormatoMoneda.
        private string Moneda(decimal valor) => valor.FormatoMoneda(ParameterService.CurrentBuilding?.Configuration.Currency);

        [Inject]
        private ParameterService ParameterService { get; set; } = default!;

        [Inject]
        private CustomAuthenticationStateProvider AuthStateProvider { get; set; } = default!;

        [Inject]
        private IIncidentService IncidentService { get; set; } = default!;

        [Inject]
        private IInstallmentService InstallmentService { get; set; } = default!;

        [Inject]
        private IBuildingService BuildingService { get; set; } = default!;

        [Inject]
        private IBankAccountService BankAccountService { get; set; } = default!;

        // Flag para controlar si ya se cargaron los datos
        private bool _isDataLoaded = false;

        // Flag para evitar múltiples llamadas simultáneas
        private bool _isLoading = false;

        // Modelos de datos
        public class ActivityItem
        {
            public string Title { get; set; } = string.Empty;
            public string Description { get; set; } = string.Empty;
            public DateTime When { get; set; }
            public string Time { get; set; } = string.Empty;
            public string User { get; set; } = string.Empty;
            public string Icon { get; set; } = string.Empty;
            public string IconColor { get; set; } = string.Empty;
            public bool IsImportant { get; set; }
        }

        public class QuickAction
        {
            public string Title { get; set; } = string.Empty;
            public string Icon { get; set; } = string.Empty;
            public string Url { get; set; } = string.Empty;
            public string Color { get; set; } = "bg-light";
        }

        public class DueItem
        {
            public string Day { get; set; } = string.Empty;
            public string Month { get; set; } = string.Empty;
            public string Title { get; set; } = string.Empty;
            public string Description { get; set; } = string.Empty;
            public string Unit { get; set; } = string.Empty;
            public string Amount { get; set; } = string.Empty;
            public string DateColor { get; set; } = "bg-secondary";
            public bool IsUrgent { get; set; }
            // Periodo de la CUOTA (mes que factura, ej. "set-2026") -- distinto del
            // Day/Month de arriba, que son de DueDate (cuándo vence). No son siempre el
            // mismo mes (ej. una cuota de un periodo vence recién el mes siguiente), y sin
            // esto no había forma de saber de qué mes era el vencimiento con solo mirar la
            // tarjeta.
            public string Periodo { get; set; } = string.Empty;
        }

        private List<ActivityItem> recentActivities = [];
        private List<DueItem> upcomingDues = [];
        private List<Models.InstallmentPaid> recentPayments = [];

        // Accesos rápidos: sólo rutas reales de la app (las de la maqueta original --
        // /pagos/nuevo, /unidades, /reportes, /mantenimiento, /comunicados,
        // /configuracion -- no existen).
        private List<QuickAction> quickActions =
        [
            new QuickAction { Title = "Presupuestos", Icon = "bi-file-earmark-spreadsheet", Url = "/budgetlist", Color = "bg-primary text-white" },
            new QuickAction { Title = "Incidencias", Icon = "bi-exclamation-triangle", Url = "/incidents", Color = "bg-warning text-white" },
            new QuickAction { Title = "Edificios", Icon = "bi-building", Url = "/buildings", Color = "bg-success text-white" },
            new QuickAction { Title = "Movimientos", Icon = "bi-bank", Url = "/movement", Color = "bg-info text-white" },
            new QuickAction { Title = "Lecturas de Agua", Icon = "bi-droplet", Url = "/waterreadings", Color = "bg-teal text-white" },
            new QuickAction { Title = "Mi Perfil", Icon = "bi-person-circle", Url = "/Profile", Color = "bg-secondary text-white" }
        ];

        // KPIs del resumen rápido -- ver LoadDashboardStatsAsync para cómo se calculan.
        private decimal _ingresosMes;
        private int _totalUnidades;
        private int _unidadesAsignadas;
        private int _incidenciasPendientes;
        private int _cuotasPendientesCount;
        private decimal _cuotasPendientesMonto;
        private int _unidadesMorosas;
        private double _morosidadPct;
        // Denominador real de Morosidad -- ver LoadDashboardStatsAsync.
        private int _totalGruposUnidad;

        // Gráfico "Ingresos y Egresos" -- antes era 100% placeholder estático (sin datos,
        // sin librería de gráficos). Fuente: movimientos bancarios reales (mismos que
        // /reports/IncomeExpenses), traídos una sola vez por carga del Dashboard y
        // re-agrupados en memoria al cambiar de rango (sin volver a golpear la BD).
        private List<Models.AccountStatementDetailView> _movimientosBancarios = new();
        private string _rangoGraficoIngresos = "anio"; // "mes" | "3meses" | "anio"
        private List<string> _graficoLabels = new();
        private List<decimal> _graficoIngresos = new();
        private List<decimal> _graficoEgresos = new();
        private bool _debeRedibujarGraficoIngresos;

        private static readonly Dictionary<string, string> RangoGraficoLabels = new()
        {
            ["mes"] = "Este Mes",
            ["3meses"] = "Últimos 3 Meses",
            ["anio"] = "Este Año"
        };
        private string RangoGraficoLabel => RangoGraficoLabels.GetValueOrDefault(_rangoGraficoIngresos, "Este Año");

        // Campanita del header: cosas que de verdad requieren atención ahora --
        // incidencias sin cerrar + cuotas ya vencidas (no toda cuota pendiente, sólo
        // las que ya pasaron su DueDate). No hay todavía una tabla de "Notification"
        // en la app -- esto es un conteo real, no una lista de notificaciones.
        private int _alertasUrgentes;

        private string _userName = "";

        protected override async Task OnInitializedAsync()
        {
            var currentUser = await AuthService.GetCurrentUserAsync();
            if (currentUser == null) return;
        }

        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                await InicializarPagina();
                StateHasChanged();
            }

            // Igual que en los reportes (ver CollectionReport.razor.OnAfterRenderAsync): el
            // <canvas> recién existe en el DOM después de que el render se aplicó, no apenas
            // se llama StateHasChanged() -- corre en CADA render, no sólo el primero, para
            // cubrir también el cambio de rango del dropdown.
            if (_debeRedibujarGraficoIngresos)
            {
                _debeRedibujarGraficoIngresos = false;
                await RenderizarGraficoIngresosAsync();
            }
        }

        protected async Task InicializarPagina()
        {
            Console.WriteLine("🏠 Home.OnInitializedAsync - Iniciando");

            try
            {
                // La sesión ahora se reconstruye de forma síncrona (sin JS interop) a
                // partir de la cookie de autenticación — ver CustomAuthenticationStateProvider.
                // Ya no hace falta reintentar con delays: si hay cookie válida, acá ya está.
                var currentUser = await AuthService.GetCurrentUserAsync();

                if (currentUser == null)
                {
                    Console.WriteLine("❌ Usuario no autenticado - Redirigiendo a login");
                    Navigation.NavigateTo("/login", true);
                    return;
                }

                _userName = currentUser.FullName?.Split(' ')[0] ?? "Usuario";
                Console.WriteLine($"✅ Usuario autenticado: {_userName}");

                if (currentUser.CurrentBuildingId == Guid.Empty)
                {
                    // El edificio preferido vive en localStorage (ver
                    // AuthService.SetDefaultBuildingAsync/TryApplyDefaultBuildingAsync), y
                    // por lo tanto sólo se puede leer una vez conectado el circuito — durante
                    // el prerender estático, IJSRuntime todavía no existe. Si redirigiéramos a
                    // /select-building ya durante el prerender (RendererInfo.IsInteractive ==
                    // false), lo haríamos con información incompleta, aunque el usuario ya
                    // tenga un edificio preferido guardado. Nos quedamos quietos hasta que el
                    // circuito esté realmente conectado para decidir con el dato completo.
                    if (!RendererInfo.IsInteractive)
                    {
                        Console.WriteLine("⏳ Prerender estático (sin JS todavía) - se decide una vez conectado el circuito");
                        return;
                    }

                    Console.WriteLine("🔎 Circuito conectado - intentando aplicar edificio/rol por defecto guardado");
                    if (await AuthService.TryApplyDefaultBuildingAsync())
                    {
                        currentUser = await AuthService.GetCurrentUserAsync() ?? currentUser;
                        Console.WriteLine($"✅ Edificio/rol por defecto aplicado: {currentUser.CurrentBuildingId} / {currentUser.Role}");
                    }
                }

                if (currentUser.CurrentBuildingId == Guid.Empty)
                {
                    Console.WriteLine("⚠️ No hay edificio seleccionado - Redirigiendo a select-building");
                    // Sin forceLoad: seguimos en el mismo circuito, así que
                    // SelectBuilding.razor reutiliza la sesión ya hidratada en memoria
                    // (misma instancia de CustomAuthenticationStateProvider) en vez de
                    // forzar una reconexión que vuelve a golpear la base de datos. Con
                    // forceLoad, una hidratación que tardara o fallara transitoriamente
                    // hacía que SelectBuilding viera currentUser == null y rebotara a
                    // /login — que a su vez, con la cookie todavía válida, rebotaba de
                    // nuevo a /dashboard, formando un ciclo infinito con este redirect.
                    Navigation.NavigateTo("/select-building");
                    return;
                }

                IdBuilding = currentUser.CurrentBuildingId;
                Console.WriteLine($"🏢 Edificio seleccionado: {IdBuilding}");

                await LoadDashboardDataAsync();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"❌ Error en OnInitializedAsync: {ex.Message}");
                _isLoading = false;
            }
        }

        protected override async Task OnParametersSetAsync()
        {
            try
            {
                var currentUser = await AuthService.GetCurrentUserAsync();

                if (currentUser?.CurrentBuildingId != null &&
                    currentUser.CurrentBuildingId != IdBuilding)
                {
                    Console.WriteLine($"🔄 Cambio de edificio detectado: {IdBuilding} -> {currentUser.CurrentBuildingId}");

                    IdBuilding = currentUser.CurrentBuildingId;
                    _isDataLoaded = false;
                    //await LoadDashboardDataAsync();
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"❌ Error en OnParametersSetAsync: {ex.Message}");
            }
        }

        private async Task LoadDashboardDataAsync()
        {
            // Prevenir múltiples cargas simultáneas
            if (_isLoading || _isDataLoaded)
            {
                Console.WriteLine($"⏭️ Carga omitida - _isLoading: {_isLoading}, _isDataLoaded: {_isDataLoaded}");
                return;
            }

            try
            {
                _isLoading = true;
                Console.WriteLine($"📊 Iniciando carga de datos para edificio: {IdBuilding}");

                // Cargar parámetros del edificio
                if (ParameterService.CurrentBuilding == null ||
                    ParameterService.CurrentBuilding.IdBuilding != IdBuilding)
                {
                    Console.WriteLine("📦 Cargando parámetros del edificio...");
                    await ParameterService.LoadParametersAsync(IdBuilding);
                    Console.WriteLine("✅ Parámetros cargados");
                }

                // Cargar estadísticas del dashboard
                Console.WriteLine("📈 Cargando estadísticas...");
                await LoadDashboardStatsAsync();
                Console.WriteLine("✅ Estadísticas cargadas");

                _isDataLoaded = true;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"❌ Error en LoadDashboardDataAsync: {ex.Message}");
                // Aquí podrías mostrar un mensaje de error al usuario
            }
            finally
            {
                _isLoading = false;
                Console.WriteLine("🏁 Carga de datos completada");
                StateHasChanged();
            }
        }

        private static readonly CultureInfo EsPe = new("es-PE");

        private async Task LoadDashboardStatsAsync()
        {
            if (IdBuilding == Guid.Empty) return;

            // Las 4 fuentes son independientes entre sí -- se piden en paralelo en vez
            // de una tras otra para no sumar sus latencias.
            var incidentsTask = IncidentService.GetIncidentsByBuildingAsync(IdBuilding);
            var pendingTask = InstallmentService.GetPendingInstallmentsAsync(IdBuilding);
            var paidTask = InstallmentService.GetInstallmentsPaidAsync(IdBuilding);
            var unitsTask = BuildingService.GetUnitsByBuildingAsync(IdBuilding);
            var ownersTask = BuildingService.GetOwnersByBuildingAsync(IdBuilding);
            var movimientosTask = BankAccountService.GetStatementDetailsByBuildingAsync(IdBuilding, null);

            await Task.WhenAll(incidentsTask, pendingTask, paidTask, unitsTask, ownersTask, movimientosTask);

            var incidents = incidentsTask.Result;
            var pending = pendingTask.Result.Where(i => i.Debt > 0).ToList();
            var paid = paidTask.Result;
            var units = unitsTask.Result;
            var owners = ownersTask.Result;
            _movimientosBancarios = movimientosTask.Result;

            var now = DateTime.Now;

            // KPI: ingresos del mes -- suma de lo efectivamente cobrado (InstallmentPaid),
            // no lo facturado, así que refleja caja real, no proyección.
            _ingresosMes = paid
                .Where(p => p.PaymentDate.Year == now.Year && p.PaymentDate.Month == now.Month)
                .Sum(p => p.Amount);

            // KPI: unidades -- "ocupada" se aproxima como "tiene al menos un
            // propietario/grupo asignado" (GetOwnersByBuildingAsync), ya que RealEstateUnit
            // no tiene un flag de ocupación propio.
            _totalUnidades = units.Count;
            _unidadesAsignadas = owners.Select(o => o.IdUnit).Distinct().Count();

            // KPI: incidencias pendientes -- todo lo que no llegó a un estado terminal.
            _incidenciasPendientes = incidents.Count(i =>
                i.Status != IncidentStatus.Closed && i.Status != IncidentStatus.Rejected);

            // KPI: cuotas pendientes -- por pedido explícito, separado de incidencias
            // (cubre Ordinarias, Extraordinarias, Multas y Mora -- ver InstallmentType).
            _cuotasPendientesCount = pending.Count;
            _cuotasPendientesMonto = pending.Sum(i => i.Debt);

            // KPI: morosidad -- % de unidades morosas por Grupo de Unidad, no por
            // RealEstateUnit individual. El numerador (_unidadesMorosas) ya agrupaba por
            // IdGroupUnit, pero el denominador usaba _totalUnidades (units.Count,
            // RealEstateUnit físicas) -- un grupo con más de una unidad (ej. depto +
            // cochera + depósito facturados juntos bajo un mismo Installment.IdGroupUnit)
            // hacía que el % saliera más bajo de lo real, porque el denominador contaba
            // esas 3 unidades por separado mientras el numerador las contaba como un solo
            // grupo moroso. _totalGruposUnidad usa el mismo campo (IdGroupUnit) que el
            // numerador, sobre "owners" (ya cargado arriba) -- grupos sin ningún
            // propietario asignado tampoco generan cuotas, así que no deberían contar acá
            // (mismo criterio que "_unidadesAsignadas", pero a nivel de grupo).
            _unidadesMorosas = pending.Select(i => i.IdGroupUnit).Distinct().Count();
            _totalGruposUnidad = owners.Select(o => o.IdGroupUnit).Distinct().Count();
            _morosidadPct = _totalGruposUnidad > 0 ? _unidadesMorosas * 100.0 / _totalGruposUnidad : 0;

            _alertasUrgentes = _incidenciasPendientes + pending.Count(i => i.DueDate.Date < now.Date);

            // Próximos vencimientos: las cuotas pendientes más próximas a vencer.
            upcomingDues = pending
                .OrderBy(i => i.DueDate)
                .Take(5)
                .Select(i => new DueItem
                {
                    Day = i.DueDate.ToString("dd"),
                    Month = i.DueDate.ToString("MMM", EsPe).TrimEnd('.').ToUpperInvariant(),
                    Title = TipoCuotaLabel(i.Type),
                    Description = string.IsNullOrWhiteSpace(i.Concept) ? i.OwnerName : i.Concept,
                    Unit = i.UnitName,
                    Amount = Moneda(i.Debt),
                    DateColor = i.DueDate.Date < now.Date ? "bg-danger" : "bg-primary",
                    IsUrgent = i.DueDate.Date < now.Date,
                    Periodo = PeriodoLabel(i.Period)
                })
                .ToList();

            // Últimos pagos registrados: los más recientes primero.
            recentPayments = paid
                .OrderByDescending(p => p.PaymentDate)
                .Take(8)
                .ToList();

            // Actividad reciente: mezcla de incidencias reportadas y pagos registrados,
            // ordenada por fecha -- no hay todavía una tabla de auditoría única que las
            // junte, así que se arma acá.
            var actividadIncidencias = incidents
                .OrderByDescending(i => i.ModifiedOn ?? i.CreatedOn)
                .Take(5)
                .Select(i => new ActivityItem
                {
                    Title = i.Status == IncidentStatus.Reported ? "Nueva incidencia reportada" : $"Incidencia {EstadoLabel(i.Status).ToLowerInvariant()}",
                    Description = i.Title,
                    When = i.ModifiedOn ?? i.CreatedOn,
                    Time = TiempoRelativo(i.ModifiedOn ?? i.CreatedOn, now),
                    User = i.ReportedByName,
                    Icon = "bi-tools",
                    IconColor = i.Status is IncidentStatus.Resolved or IncidentStatus.Closed ? "bg-success" : "bg-warning",
                    IsImportant = i.Status == IncidentStatus.Reported
                });

            // InstallmentPaid ya trae UnitName/OwnerName/Period por el JOIN a Installment en
            // GET_InstallmentPaid (mismos campos que ya usa el detalle de conciliación) --
            // antes esto se descartaba acá y sólo quedaba el monto, así que "Pago
            // registrado" no decía de quién ni de qué cuota.
            var actividadPagos = paid
                .OrderByDescending(p => p.PaymentDate)
                .Take(5)
                .Select(p => new ActivityItem
                {
                    Title = p.IsPartialPayment ? "Pago parcial registrado" : "Pago registrado",
                    Description = $"{Moneda(p.Amount)} -- {p.UnitName} (Cuota {PeriodoLabel(p.Period)})",
                    When = p.PaymentDate,
                    Time = TiempoRelativo(p.PaymentDate, now),
                    User = p.OwnerName,
                    Icon = "bi-cash-coin",
                    IconColor = "bg-success",
                    IsImportant = false
                });

            recentActivities = actividadIncidencias
                .Concat(actividadPagos)
                .OrderByDescending(a => a.When)
                .Take(6)
                .ToList();

            RecalcularGraficoIngresos();
        }

        // Recalcula en memoria (sin ir a BD) la serie mensual de Ingresos/Egresos del
        // gráfico del Dashboard, a partir de _movimientosBancarios (ya cargado en
        // LoadDashboardStatsAsync) -- se llama tanto al cargar el Dashboard como al cambiar
        // el rango del dropdown, sin repetir la consulta.
        private void RecalcularGraficoIngresos()
        {
            var hoy = DateTime.Today;
            DateTime desde = _rangoGraficoIngresos switch
            {
                "mes" => new DateTime(hoy.Year, hoy.Month, 1),
                "3meses" => new DateTime(hoy.Year, hoy.Month, 1).AddMonths(-2),
                _ => new DateTime(hoy.Year, 1, 1)
            };

            var porMes = _movimientosBancarios
                .Where(d => d.StatementDate.Date >= desde.Date && d.StatementDate.Date <= hoy.Date)
                .GroupBy(d => new { d.StatementDate.Year, d.StatementDate.Month })
                .OrderBy(g => g.Key.Year).ThenBy(g => g.Key.Month)
                .Select(g => new
                {
                    Periodo = PeriodoLabel(new DateTime(g.Key.Year, g.Key.Month, 1)),
                    Ingresos = g.Where(d => d.Amount > 0).Sum(d => d.Amount),
                    Egresos = g.Where(d => d.Amount < 0).Sum(d => Math.Abs(d.Amount))
                })
                .ToList();

            _graficoLabels = porMes.Select(p => p.Periodo).ToList();
            _graficoIngresos = porMes.Select(p => p.Ingresos).ToList();
            _graficoEgresos = porMes.Select(p => p.Egresos).ToList();

            _debeRedibujarGraficoIngresos = _graficoLabels.Any();
        }

        private async Task CambiarRangoGraficoIngresos(string rango)
        {
            if (_rangoGraficoIngresos == rango) return;
            _rangoGraficoIngresos = rango;
            RecalcularGraficoIngresos();
            StateHasChanged();

            // RecalcularGraficoIngresos ya dejó _debeRedibujarGraficoIngresos en true --
            // OnAfterRenderAsync lo dibuja después de este StateHasChanged. Pero si el
            // rango nuevo no tiene ningún movimiento, no hay próximo <canvas> que dibujar
            // (el markup cae en la rama "sin datos"), así que no queda ningún redibujado
            // pendiente -- y JS no puede fallar en falso porque nunca se llega a invocar.
            await Task.CompletedTask;
        }

        private async Task RenderizarGraficoIngresosAsync()
        {
            if (!_graficoLabels.Any()) return;

            var datasets = new[]
            {
                new { label = "Ingresos", data = _graficoIngresos.ToArray(), color = "rgba(25, 135, 84, 0.9)", dashed = false },
                new { label = "Egresos", data = _graficoEgresos.ToArray(), color = "rgba(220, 53, 69, 0.9)", dashed = false }
            };

            try
            {
                await JSRuntime.InvokeVoidAsync("spiderHoodReportCharts.lineChart", "chartIngresosDashboard", _graficoLabels, datasets, null);
            }
            catch (JSDisconnectedException)
            {
                // Circuito cerrándose (navegación afuera del Dashboard) -- nada que hacer.
            }
            catch (InvalidOperationException)
            {
                // Prerender estático -- ver el comentario equivalente en
                // CollectionReport.razor.RenderizarGraficoAsync.
            }
        }

        // Mismo formato que el Month del due-date box (MMM, sin el punto de es-PE), pero
        // en minúscula + año -- para distinguir a simple vista "vence el día X" (Day/Month)
        // de "es la cuota de qué mes" (Periodo), que no siempre coinciden.
        private static string PeriodoLabel(DateTime period) => $"{period.ToString("MMM", EsPe).TrimEnd('.')}-{period:yyyy}";

        private static string TipoCuotaLabel(InstallmentType type) => type switch
        {
            InstallmentType.Ordinaria => "Cuota Ordinaria",
            InstallmentType.Extraordinaria => "Cuota Extraordinaria",
            InstallmentType.Multa => "Multa",
            InstallmentType.Mora => "Mora",
            _ => "Cuota"
        };

        private static string EstadoLabel(IncidentStatus status) => status switch
        {
            IncidentStatus.Reported => "Reportada",
            IncidentStatus.InReview => "En revisión",
            IncidentStatus.InProgress => "En progreso",
            IncidentStatus.Resolved => "Resuelta",
            IncidentStatus.Closed => "Cerrada",
            IncidentStatus.Rejected => "Rechazada",
            IncidentStatus.Reopened => "Reabierta",
            _ => status.ToString()
        };

        private static string TiempoRelativo(DateTime fecha, DateTime ahora)
        {
            var diff = ahora - fecha;
            if (diff.TotalMinutes < 1) return "Recién";
            if (diff.TotalMinutes < 60) return $"Hace {(int)diff.TotalMinutes} min";
            if (diff.TotalHours < 24) return $"Hace {(int)diff.TotalHours} h";
            if (diff.TotalDays < 7) return $"Hace {(int)diff.TotalDays} d";
            return fecha.ToString("dd/MM/yyyy");
        }

        // Método para refrescar datos manualmente
        private async Task RefreshDashboard()
        {
            _isDataLoaded = false;
            await LoadDashboardDataAsync();
            StateHasChanged();
        }

        // La campanita no abre un feed de notificaciones (no existe todavía ese
        // concepto en la app) -- lleva directo a Incidencias, que es de donde sale la
        // mayor parte de _alertasUrgentes.
        private void GoToAlertas() => Navigation.NavigateTo("/incidents");
    }
}
