// <autogenerated />
using Microsoft.AspNetCore.Components;
using SpiderHood.Models;
using SpiderHood.Services;
using System.Globalization;

namespace SpiderHood.Components.Pages
{
    public partial class Home
    {
        private Guid IdBuilding = Guid.Empty;

        [Inject]
        private ParameterService ParameterService { get; set; } = default!;

        [Inject]
        private CustomAuthenticationStateProvider AuthStateProvider { get; set; } = default!;

        [Inject]
        private IIncidentService IncidentService { get; set; } = default!;

        [Inject]
        private IInstallmentService InstallmentService { get; set; } = default!;

        [Inject]
        private IBuildingService BuildingService { get; set; } = default!;

        // Flag para controlar si ya se cargaron los datos
        private bool _isDataLoaded = false;

        // Flag para evitar múltiples llamadas simultáneas
        private bool _isLoading = false;

        // Modelos de datos
        public class ActivityItem
        {
            public string Title { get; set; } = string.Empty;
            public string Description { get; set; } = string.Empty;
            public DateTime When { get; set; }
            public string Time { get; set; } = string.Empty;
            public string User { get; set; } = string.Empty;
            public string Icon { get; set; } = string.Empty;
            public string IconColor { get; set; } = string.Empty;
            public bool IsImportant { get; set; }
        }

        public class QuickAction
        {
            public string Title { get; set; } = string.Empty;
            public string Icon { get; set; } = string.Empty;
            public string Url { get; set; } = string.Empty;
            public string Color { get; set; } = "bg-light";
        }

        public class DueItem
        {
            public string Day { get; set; } = string.Empty;
            public string Month { get; set; } = string.Empty;
            public string Title { get; set; } = string.Empty;
            public string Description { get; set; } = string.Empty;
            public string Unit { get; set; } = string.Empty;
            public string Amount { get; set; } = string.Empty;
            public string DateColor { get; set; } = "bg-secondary";
            public bool IsUrgent { get; set; }
        }

        private List<ActivityItem> recentActivities = [];
        private List<DueItem> upcomingDues = [];
        private List<Models.InstallmentPaid> recentPayments = [];

        // Accesos rápidos: sólo rutas reales de la app (las de la maqueta original --
        // /pagos/nuevo, /unidades, /reportes, /mantenimiento, /comunicados,
        // /configuracion -- no existen).
        private List<QuickAction> quickActions =
        [
            new QuickAction { Title = "Presupuestos", Icon = "bi-file-earmark-spreadsheet", Url = "/budgetlist", Color = "bg-primary text-white" },
            new QuickAction { Title = "Incidencias", Icon = "bi-exclamation-triangle", Url = "/incidents", Color = "bg-warning text-white" },
            new QuickAction { Title = "Edificios", Icon = "bi-building", Url = "/buildings", Color = "bg-success text-white" },
            new QuickAction { Title = "Movimientos", Icon = "bi-bank", Url = "/movement", Color = "bg-info text-white" },
            new QuickAction { Title = "Lecturas de Agua", Icon = "bi-droplet", Url = "/waterreadings", Color = "bg-teal text-white" },
            new QuickAction { Title = "Mi Perfil", Icon = "bi-person-circle", Url = "/Profile", Color = "bg-secondary text-white" }
        ];

        // KPIs del resumen rápido -- ver LoadDashboardStatsAsync para cómo se calculan.
        private decimal _ingresosMes;
        private int _totalUnidades;
        private int _unidadesAsignadas;
        private int _incidenciasPendientes;
        private int _cuotasPendientesCount;
        private decimal _cuotasPendientesMonto;
        private int _unidadesMorosas;
        private double _morosidadPct;

        private string _userName = "";

        protected override async Task OnInitializedAsync()
        {
            var currentUser = await AuthService.GetCurrentUserAsync();
            if (currentUser == null) return;
        }

        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                await InicializarPagina();
                StateHasChanged();
            }
        }

        protected async Task InicializarPagina()
        {
            Console.WriteLine("🏠 Home.OnInitializedAsync - Iniciando");

            try
            {
                // La sesión ahora se reconstruye de forma síncrona (sin JS interop) a
                // partir de la cookie de autenticación — ver CustomAuthenticationStateProvider.
                // Ya no hace falta reintentar con delays: si hay cookie válida, acá ya está.
                var currentUser = await AuthService.GetCurrentUserAsync();

                if (currentUser == null)
                {
                    Console.WriteLine("❌ Usuario no autenticado - Redirigiendo a login");
                    Navigation.NavigateTo("/login", true);
                    return;
                }

                _userName = currentUser.FullName?.Split(' ')[0] ?? "Usuario";
                Console.WriteLine($"✅ Usuario autenticado: {_userName}");

                if (currentUser.CurrentBuildingId == Guid.Empty)
                {
                    // El edificio preferido vive en localStorage (ver
                    // AuthService.SetDefaultBuildingAsync/TryApplyDefaultBuildingAsync), y
                    // por lo tanto sólo se puede leer una vez conectado el circuito — durante
                    // el prerender estático, IJSRuntime todavía no existe. Si redirigiéramos a
                    // /select-building ya durante el prerender (RendererInfo.IsInteractive ==
                    // false), lo haríamos con información incompleta, aunque el usuario ya
                    // tenga un edificio preferido guardado. Nos quedamos quietos hasta que el
                    // circuito esté realmente conectado para decidir con el dato completo.
                    if (!RendererInfo.IsInteractive)
                    {
                        Console.WriteLine("⏳ Prerender estático (sin JS todavía) - se decide una vez conectado el circuito");
                        return;
                    }

                    Console.WriteLine("🔎 Circuito conectado - intentando aplicar edificio/rol por defecto guardado");
                    if (await AuthService.TryApplyDefaultBuildingAsync())
                    {
                        currentUser = await AuthService.GetCurrentUserAsync() ?? currentUser;
                        Console.WriteLine($"✅ Edificio/rol por defecto aplicado: {currentUser.CurrentBuildingId} / {currentUser.Role}");
                    }
                }

                if (currentUser.CurrentBuildingId == Guid.Empty)
                {
                    Console.WriteLine("⚠️ No hay edificio seleccionado - Redirigiendo a select-building");
                    // Sin forceLoad: seguimos en el mismo circuito, así que
                    // SelectBuilding.razor reutiliza la sesión ya hidratada en memoria
                    // (misma instancia de CustomAuthenticationStateProvider) en vez de
                    // forzar una reconexión que vuelve a golpear la base de datos. Con
                    // forceLoad, una hidratación que tardara o fallara transitoriamente
                    // hacía que SelectBuilding viera currentUser == null y rebotara a
                    // /login — que a su vez, con la cookie todavía válida, rebotaba de
                    // nuevo a /dashboard, formando un ciclo infinito con este redirect.
                    Navigation.NavigateTo("/select-building");
                    return;
                }

                IdBuilding = currentUser.CurrentBuildingId;
                Console.WriteLine($"🏢 Edificio seleccionado: {IdBuilding}");

                await LoadDashboardDataAsync();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"❌ Error en OnInitializedAsync: {ex.Message}");
                _isLoading = false;
            }
        }

        protected override async Task OnParametersSetAsync()
        {
            try
            {
                var currentUser = await AuthService.GetCurrentUserAsync();

                if (currentUser?.CurrentBuildingId != null &&
                    currentUser.CurrentBuildingId != IdBuilding)
                {
                    Console.WriteLine($"🔄 Cambio de edificio detectado: {IdBuilding} -> {currentUser.CurrentBuildingId}");

                    IdBuilding = currentUser.CurrentBuildingId;
                    _isDataLoaded = false;
                    //await LoadDashboardDataAsync();
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"❌ Error en OnParametersSetAsync: {ex.Message}");
            }
        }

        private async Task LoadDashboardDataAsync()
        {
            // Prevenir múltiples cargas simultáneas
            if (_isLoading || _isDataLoaded)
            {
                Console.WriteLine($"⏭️ Carga omitida - _isLoading: {_isLoading}, _isDataLoaded: {_isDataLoaded}");
                return;
            }

            try
            {
                _isLoading = true;
                Console.WriteLine($"📊 Iniciando carga de datos para edificio: {IdBuilding}");

                // Cargar parámetros del edificio
                if (ParameterService.CurrentBuilding == null ||
                    ParameterService.CurrentBuilding.IdBuilding != IdBuilding)
                {
                    Console.WriteLine("📦 Cargando parámetros del edificio...");
                    await ParameterService.LoadParametersAsync(IdBuilding);
                    Console.WriteLine("✅ Parámetros cargados");
                }

                // Cargar estadísticas del dashboard
                Console.WriteLine("📈 Cargando estadísticas...");
                await LoadDashboardStatsAsync();
                Console.WriteLine("✅ Estadísticas cargadas");

                _isDataLoaded = true;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"❌ Error en LoadDashboardDataAsync: {ex.Message}");
                // Aquí podrías mostrar un mensaje de error al usuario
            }
            finally
            {
                _isLoading = false;
                Console.WriteLine("🏁 Carga de datos completada");
                StateHasChanged();
            }
        }

        private static readonly CultureInfo EsPe = new("es-PE");

        private async Task LoadDashboardStatsAsync()
        {
            if (IdBuilding == Guid.Empty) return;

            // Las 4 fuentes son independientes entre sí -- se piden en paralelo en vez
            // de una tras otra para no sumar sus latencias.
            var incidentsTask = IncidentService.GetIncidentsByBuildingAsync(IdBuilding);
            var pendingTask = InstallmentService.GetPendingInstallmentsAsync(IdBuilding);
            var paidTask = InstallmentService.GetInstallmentsPaidAsync(IdBuilding);
            var unitsTask = BuildingService.GetUnitsByBuildingAsync(IdBuilding);
            var ownersTask = BuildingService.GetOwnersByBuildingAsync(IdBuilding);

            await Task.WhenAll(incidentsTask, pendingTask, paidTask, unitsTask, ownersTask);

            var incidents = incidentsTask.Result;
            var pending = pendingTask.Result.Where(i => i.Debt > 0).ToList();
            var paid = paidTask.Result;
            var units = unitsTask.Result;
            var owners = ownersTask.Result;

            var now = DateTime.Now;

            // KPI: ingresos del mes -- suma de lo efectivamente cobrado (InstallmentPaid),
            // no lo facturado, así que refleja caja real, no proyección.
            _ingresosMes = paid
                .Where(p => p.PaymentDate.Year == now.Year && p.PaymentDate.Month == now.Month)
                .Sum(p => p.Amount);

            // KPI: unidades -- "ocupada" se aproxima como "tiene al menos un
            // propietario/grupo asignado" (GetOwnersByBuildingAsync), ya que RealEstateUnit
            // no tiene un flag de ocupación propio.
            _totalUnidades = units.Count;
            _unidadesAsignadas = owners.Select(o => o.IdUnit).Distinct().Count();

            // KPI: incidencias pendientes -- todo lo que no llegó a un estado terminal.
            _incidenciasPendientes = incidents.Count(i =>
                i.Status != IncidentStatus.Closed && i.Status != IncidentStatus.Rejected);

            // KPI: cuotas pendientes -- por pedido explícito, separado de incidencias
            // (cubre Ordinarias, Extraordinarias, Multas y Mora -- ver InstallmentType).
            _cuotasPendientesCount = pending.Count;
            _cuotasPendientesMonto = pending.Sum(i => i.Debt);

            // KPI: morosidad -- % de unidades (por grupo de unidad) con al menos una
            // cuota vencida sobre el total de unidades del edificio.
            _unidadesMorosas = pending.Select(i => i.IdGroupUnit).Distinct().Count();
            _morosidadPct = _totalUnidades > 0 ? _unidadesMorosas * 100.0 / _totalUnidades : 0;

            // Próximos vencimientos: las cuotas pendientes más próximas a vencer.
            upcomingDues = pending
                .OrderBy(i => i.DueDate)
                .Take(5)
                .Select(i => new DueItem
                {
                    Day = i.DueDate.ToString("dd"),
                    Month = i.DueDate.ToString("MMM", EsPe).TrimEnd('.').ToUpperInvariant(),
                    Title = TipoCuotaLabel(i.Type),
                    Description = string.IsNullOrWhiteSpace(i.Concept) ? i.OwnerName : i.Concept,
                    Unit = i.UnitName,
                    Amount = i.Debt.ToString("C"),
                    DateColor = i.DueDate.Date < now.Date ? "bg-danger" : "bg-primary",
                    IsUrgent = i.DueDate.Date < now.Date
                })
                .ToList();

            // Últimos pagos registrados: los más recientes primero.
            recentPayments = paid
                .OrderByDescending(p => p.PaymentDate)
                .Take(8)
                .ToList();

            // Actividad reciente: mezcla de incidencias reportadas y pagos registrados,
            // ordenada por fecha -- no hay todavía una tabla de auditoría única que las
            // junte, así que se arma acá.
            var actividadIncidencias = incidents
                .OrderByDescending(i => i.ModifiedOn ?? i.CreatedOn)
                .Take(5)
                .Select(i => new ActivityItem
                {
                    Title = i.Status == IncidentStatus.Reported ? "Nueva incidencia reportada" : $"Incidencia {EstadoLabel(i.Status).ToLowerInvariant()}",
                    Description = i.Title,
                    When = i.ModifiedOn ?? i.CreatedOn,
                    Time = TiempoRelativo(i.ModifiedOn ?? i.CreatedOn, now),
                    User = i.ReportedByName,
                    Icon = "bi-tools",
                    IconColor = i.Status is IncidentStatus.Resolved or IncidentStatus.Closed ? "bg-success" : "bg-warning",
                    IsImportant = i.Status == IncidentStatus.Reported
                });

            var actividadPagos = paid
                .OrderByDescending(p => p.PaymentDate)
                .Take(5)
                .Select(p => new ActivityItem
                {
                    Title = p.IsPartialPayment ? "Pago parcial registrado" : "Pago registrado",
                    Description = p.Amount.ToString("C"),
                    When = p.PaymentDate,
                    Time = TiempoRelativo(p.PaymentDate, now),
                    User = string.Empty,
                    Icon = "bi-cash-coin",
                    IconColor = "bg-success",
                    IsImportant = false
                });

            recentActivities = actividadIncidencias
                .Concat(actividadPagos)
                .OrderByDescending(a => a.When)
                .Take(6)
                .ToList();
        }

        private static string TipoCuotaLabel(InstallmentType type) => type switch
        {
            InstallmentType.Ordinaria => "Cuota Ordinaria",
            InstallmentType.Extraordinaria => "Cuota Extraordinaria",
            InstallmentType.Multa => "Multa",
            InstallmentType.Mora => "Mora",
            _ => "Cuota"
        };

        private static string EstadoLabel(IncidentStatus status) => status switch
        {
            IncidentStatus.Reported => "Reportada",
            IncidentStatus.InReview => "En revisión",
            IncidentStatus.InProgress => "En progreso",
            IncidentStatus.Resolved => "Resuelta",
            IncidentStatus.Closed => "Cerrada",
            IncidentStatus.Rejected => "Rechazada",
            IncidentStatus.Reopened => "Reabierta",
            _ => status.ToString()
        };

        private static string TiempoRelativo(DateTime fecha, DateTime ahora)
        {
            var diff = ahora - fecha;
            if (diff.TotalMinutes < 1) return "Recién";
            if (diff.TotalMinutes < 60) return $"Hace {(int)diff.TotalMinutes} min";
            if (diff.TotalHours < 24) return $"Hace {(int)diff.TotalHours} h";
            if (diff.TotalDays < 7) return $"Hace {(int)diff.TotalDays} d";
            return fecha.ToString("dd/MM/yyyy");
        }

        // Método para refrescar datos manualmente
        private async Task RefreshDashboard()
        {
            _isDataLoaded = false;
            await LoadDashboardDataAsync();
            StateHasChanged();
        }

        // Método para manejar notificaciones
        private void ToggleNotifications()
        {
            // Lógica para mostrar notificaciones
        }
    }
}
