// <autogenerated />
using Microsoft.AspNetCore.Components;
using SpiderHood.Models;
using SpiderHood.Services;

namespace SpiderHood.Components.Pages
{
    public partial class Home
    {
        /* Variables existentes... */
        private Guid IdBuilding = Guid.Empty;

        [Inject]
        private ParameterService ParameterService { get; set; } = default!;

        [Inject]
        private CustomAuthenticationStateProvider AuthStateProvider { get; set; } = default!;

        // Flag para controlar si ya se cargaron los datos
        private bool _isDataLoaded = false;

        // Flag para evitar múltiples llamadas simultáneas
        private bool _isLoading = false;

        // Datos cacheados para evitar recargas
        private Dictionary<string, object> _cachedData = new();

        // Modelos de datos
        public class ActivityItem
        {
            public string Title { get; set; } = string.Empty;
            public string Description { get; set; } = string.Empty;
            public string Time { get; set; } = string.Empty;
            public string User { get; set; } = string.Empty;
            public string Icon { get; set; } = string.Empty;
            public string IconColor { get; set; } = string.Empty;
            public bool IsImportant { get; set; }
        }

        public class QuickAction
        {
            public string Title { get; set; } = string.Empty;
            public string Icon { get; set; } = string.Empty;
            public string Url { get; set; } = string.Empty;
            public string Color { get; set; } = "bg-light";
        }

        public class DueItem
        {
            public string Day { get; set; } = string.Empty;
            public string Month { get; set; } = string.Empty;
            public string Title { get; set; } = string.Empty;
            public string Description { get; set; } = string.Empty;
            public string Unit { get; set; } = string.Empty;
            public string Amount { get; set; } = string.Empty;
            public string DateColor { get; set; } = "bg-secondary";
            public bool IsUrgent { get; set; }
        }

        public class Payment
        {
            public DateTime Date { get; set; }
            public string Unit { get; set; } = string.Empty;
            public string Owner { get; set; } = string.Empty;
            public string Concept { get; set; } = string.Empty;
            public decimal Amount { get; set; }
            public string Status { get; set; } = string.Empty;
            public string StatusClass { get; set; } = string.Empty;
        }

        // Datos de ejemplo
        private List<ActivityItem> recentActivities = new()
    {
        new ActivityItem
        {
            Title = "Pago registrado",
            Description = "Mantenimiento mensual DEP-301",
            Time = "Hace 15 min",
            User = "Carlos Ruiz",
            Icon = "bi-cash-coin",
            IconColor = "bg-success",
            IsImportant = false
        },
        new ActivityItem
        {
            Title = "Nueva solicitud",
            Description = "Reparación de fuga de agua",
            Time = "Hace 1 hora",
            User = "Ana Martínez",
            Icon = "bi-tools",
            IconColor = "bg-warning",
            IsImportant = true
        },
        new ActivityItem
        {
            Title = "Alerta de morosidad",
            Description = "3 unidades con pago pendiente",
            Time = "Hace 2 horas",
            User = "Sistema",
            Icon = "bi-exclamation-triangle",
            IconColor = "bg-danger",
            IsImportant = true
        },
        new ActivityItem
        {
            Title = "Reporte generado",
            Description = "Estado de cuentas mensual",
            Time = "Hace 4 horas",
            User = "Administración",
            Icon = "bi-file-earmark-text",
            IconColor = "bg-info",
            IsImportant = false
        }
    };

        private List<QuickAction> quickActions = new()
    {
        new QuickAction { Title = "Nuevo Pago", Icon = "bi-cash", Url = "/pagos/nuevo", Color = "bg-success text-white" },
        new QuickAction { Title = "Unidades", Icon = "bi-building", Url = "/unidades", Color = "bg-primary text-white" },
        new QuickAction { Title = "Reportes", Icon = "bi-graph-up", Url = "/reportes", Color = "bg-info text-white" },
        new QuickAction { Title = "Mantenimiento", Icon = "bi-tools", Url = "/mantenimiento", Color = "bg-warning text-white" },
        new QuickAction { Title = "Comunicados", Icon = "bi-megaphone", Url = "/comunicados", Color = "bg-purple text-white" },
        new QuickAction { Title = "Configuración", Icon = "bi-gear", Url = "/configuracion", Color = "bg-secondary text-white" }
    };

        private List<DueItem> upcomingDues = new()
    {
        new DueItem { Day = "15", Month = "ENE", Title = "Mantenimiento", Description = "Pago mensual", Unit = "DEP-201", Amount = "S/. 250", DateColor = "bg-primary", IsUrgent = true },
        new DueItem { Day = "18", Month = "ENE", Title = "Agua", Description = "Factura mensual", Unit = "Todo el edificio", Amount = "S/. 1,850", DateColor = "bg-info", IsUrgent = false },
        new DueItem { Day = "20", Month = "ENE", Title = "Luz común", Description = "Factura eléctrica", Unit = "Áreas comunes", Amount = "S/. 2,300", DateColor = "bg-warning", IsUrgent = false },
        new DueItem { Day = "25", Month = "ENE", Title = "Seguridad", Description = "Servicio mensual", Unit = "Vigilancia", Amount = "S/. 3,500", DateColor = "bg-secondary", IsUrgent = false }
    };

        private List<Payment> recentPayments = new()
    {
        new Payment { Date = DateTime.Now.AddDays(-1), Unit = "DEP-101", Owner = "María González", Concept = "Mantenimiento", Amount = 250, Status = "Completado", StatusClass = "bg-success" },
        new Payment { Date = DateTime.Now.AddDays(-2), Unit = "DEP-205", Owner = "Juan Pérez", Concept = "Agua", Amount = 85, Status = "Completado", StatusClass = "bg-success" },
        new Payment { Date = DateTime.Now.AddDays(-3), Unit = "DEP-308", Owner = "Laura Silva", Concept = "Mantenimiento", Amount = 250, Status = "Pendiente", StatusClass = "bg-warning" },
        new Payment { Date = DateTime.Now.AddDays(-4), Unit = "LOC-01", Owner = "TechStore SAC", Concept = "Alquiler", Amount = 1500, Status = "Completado", StatusClass = "bg-success" },
        new Payment { Date = DateTime.Now.AddDays(-5), Unit = "DEP-412", Owner = "Roberto Díaz", Concept = "Multa", Amount = 100, Status = "Rechazado", StatusClass = "bg-danger" }
    };

        private string _userName = "";

        protected override async Task OnInitializedAsync()
        {
            var currentUser = await AuthService.GetCurrentUserAsync();
            if (currentUser == null) return;
        }

        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                await InicializarPagina();
                StateHasChanged();
            }
        }

        protected async Task InicializarPagina()
        {
            Console.WriteLine("🏠 Home.OnInitializedAsync - Iniciando");

            try
            {
                // La sesión ahora se reconstruye de forma síncrona (sin JS interop) a
                // partir de la cookie de autenticación — ver CustomAuthenticationStateProvider.
                // Ya no hace falta reintentar con delays: si hay cookie válida, acá ya está.
                var currentUser = await AuthService.GetCurrentUserAsync();

                if (currentUser == null)
                {
                    Console.WriteLine("❌ Usuario no autenticado - Redirigiendo a login");
                    Navigation.NavigateTo("/login", true);
                    return;
                }

                _userName = currentUser.FullName?.Split(' ')[0] ?? "Usuario";
                Console.WriteLine($"✅ Usuario autenticado: {_userName}");

                if (currentUser.CurrentBuildingId == Guid.Empty)
                {
                    // El edificio preferido vive en localStorage (ver
                    // AuthService.SetDefaultBuildingAsync/TryApplyDefaultBuildingAsync), y
                    // por lo tanto sólo se puede leer una vez conectado el circuito — durante
                    // el prerender estático, IJSRuntime todavía no existe. Si redirigiéramos a
                    // /select-building ya durante el prerender (RendererInfo.IsInteractive ==
                    // false), lo haríamos con información incompleta, aunque el usuario ya
                    // tenga un edificio preferido guardado. Nos quedamos quietos hasta que el
                    // circuito esté realmente conectado para decidir con el dato completo.
                    if (!RendererInfo.IsInteractive)
                    {
                        return;
                    }

                    if (await AuthService.TryApplyDefaultBuildingAsync())
                    {
                        currentUser = await AuthService.GetCurrentUserAsync() ?? currentUser;
                    }
                }

                if (currentUser.CurrentBuildingId == Guid.Empty)
                {
                    Console.WriteLine("⚠️ No hay edificio seleccionado - Redirigiendo a select-building");
                    // Sin forceLoad: seguimos en el mismo circuito, así que
                    // SelectBuilding.razor reutiliza la sesión ya hidratada en memoria
                    // (misma instancia de CustomAuthenticationStateProvider) en vez de
                    // forzar una reconexión que vuelve a golpear la base de datos. Con
                    // forceLoad, una hidratación que tardara o fallara transitoriamente
                    // hacía que SelectBuilding viera currentUser == null y rebotara a
                    // /login — que a su vez, con la cookie todavía válida, rebotaba de
                    // nuevo a /dashboard, formando un ciclo infinito con este redirect.
                    Navigation.NavigateTo("/select-building");
                    return;
                }

                IdBuilding = currentUser.CurrentBuildingId;
                Console.WriteLine($"🏢 Edificio seleccionado: {IdBuilding}");

                await LoadDashboardDataAsync();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"❌ Error en OnInitializedAsync: {ex.Message}");
                _isLoading = false;
            }
        }

        protected override async Task OnParametersSetAsync()
        {
            try
            {
                var currentUser = await AuthService.GetCurrentUserAsync();

                if (currentUser?.CurrentBuildingId != null &&
                    currentUser.CurrentBuildingId != IdBuilding)
                {
                    Console.WriteLine($"🔄 Cambio de edificio detectado: {IdBuilding} -> {currentUser.CurrentBuildingId}");

                    IdBuilding = currentUser.CurrentBuildingId;
                    _isDataLoaded = false;
                    //await LoadDashboardDataAsync();
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"❌ Error en OnParametersSetAsync: {ex.Message}");
            }
        }

        private async Task LoadDashboardDataAsync()
        {
            // Prevenir múltiples cargas simultáneas
            if (_isLoading || _isDataLoaded)
            {
                Console.WriteLine($"⏭️ Carga omitida - _isLoading: {_isLoading}, _isDataLoaded: {_isDataLoaded}");
                return;
            }

            try
            {
                _isLoading = true;
                Console.WriteLine($"📊 Iniciando carga de datos para edificio: {IdBuilding}");

                // Cargar parámetros del edificio
                if (ParameterService.CurrentBuilding == null ||
                    ParameterService.CurrentBuilding.IdBuilding != IdBuilding)
                {
                    Console.WriteLine("📦 Cargando parámetros del edificio...");
                    await ParameterService.LoadParametersAsync(IdBuilding);
                    Console.WriteLine("✅ Parámetros cargados");
                }

                // Cargar estadísticas del dashboard
                Console.WriteLine("📈 Cargando estadísticas...");
                await LoadDashboardStatsAsync();
                Console.WriteLine("✅ Estadísticas cargadas");

                _isDataLoaded = true;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"❌ Error en LoadDashboardDataAsync: {ex.Message}");
                // Aquí podrías mostrar un mensaje de error al usuario
            }
            finally
            {
                _isLoading = false;
                Console.WriteLine("🏁 Carga de datos completada");
                StateHasChanged();
            }
        }

        private async Task LoadDashboardStatsAsync()
        {
            // Simular carga de estadísticas
            //await Task.Delay(100); // Quitar en producción

            // Aquí irían las llamadas reales a tus servicios
            // Ejemplo:
            // recentActivities = await _activityService.GetRecentActivitiesAsync(IdBuilding);
            // recentPayments = await _paymentService.GetRecentPaymentsAsync(IdBuilding);
        }

        // Método para refrescar datos manualmente
        private async Task RefreshDashboard()
        {
            _isDataLoaded = false;
            await LoadDashboardDataAsync();
            StateHasChanged();
        }

        // Método para manejar notificaciones
        private void ToggleNotifications()
        {
            // Lógica para mostrar notificaciones
        }
    }
}