// <autogenerated />
#nullable enable
using BlazorBootstrap;
using Microsoft.AspNetCore.Components;
using SpiderHood.Components.Pages.Components;
using SpiderHood.Models;
using SpiderHood.Utilities;

namespace SpiderHood.Components.Pages.CommunicationPages
{
    public partial class Announcements
    {
        private bool _loading = true;
        private bool _canPublicar;
        private UserSession currentUser = new();

        private AnnouncementPagination _pagination = new();
        private string _searchTerm = string.Empty;
        private int _pageSize = 25;

        private int _idCategoriaAnnouncement;
        private List<Parameter> _categorias = new();
        private List<UnitView> _unidades = new();
        private HashSet<Guid> _unidadesSeleccionadas = new();

        private Announcement _form = new();
        private bool _publicando;
        private string? _resultado;
        private bool _resultadoOk;

        // Distinto de _resultado -- ese alert vive en el cuerpo de la página y queda
        // tapado por el backdrop del Modal mientras está abierto (feedback del usuario
        // 2026-09-12: "el mensaje sale por atrás, no se ve"). Los errores de validación
        // que ocurren CON el modal todavía abierto se muestran acá adentro en su lugar.
        private string? _errorModal;

        private List<AnnouncementRecipient> _destinatarios = new();
        private Announcement? _comunicadoSeleccionado;

        private Modal _nuevoModal = null!;
        private Modal _detalleModal = null!;
        private ConfirmationModal? _confirmationModal;
        private readonly ConfirmationUtil _util = new();

        protected override async Task OnInitializedAsync()
        {
            currentUser = await AuthService.GetCurrentUserAsync() ?? new UserSession();
            _canPublicar = await PermissionService.HasPermissionAsync(currentUser, "create_announcements");

            if (_canPublicar && currentUser.CurrentBuildingId != Guid.Empty)
            {
                await ParameterService.LoadParametersAsync(currentUser.CurrentBuildingId);

                // El grupo "Categoría Comunicado" lo crea el script de la migración con
                // IdParent=0 -- su IdTabla real lo asigna SQL Server (IDENTITY), así que
                // se resuelve acá por ShortDescription en vez de asumir un número fijo
                // (a diferencia de grupos viejos como "Tipo Edificio", que sí quedaron
                // hardcodeados en otras pantallas porque ya existían de antes).
                _idCategoriaAnnouncement = ParameterService.ListParameters
                    .FirstOrDefault(p => p.IdParent == 0 && p.ShortDescription == "Categoría Comunicado")?.IdTabla ?? 0;
                _categorias = ParameterService.ListParameters
                    .Where(p => p.IdParent == _idCategoriaAnnouncement)
                    .OrderBy(p => p.Sort)
                    .ToList();

                // Una unidad sin propietario/grupo asignado (IdGroupUnit null) no tiene a
                // quién notificarle un Announcement Privado -- se excluye del selector.
                _unidades = (await BuildingService.GetGroupUnitsByTypeAsync(currentUser.CurrentBuildingId, 1))
                    .Where(u => u.IdGroupUnit.HasValue)
                    .ToList();

                await CargarAnnouncementsAsync();
            }

            _loading = false;
        }

        private async Task CargarAnnouncementsAsync()
        {
            var comunicados = await AnnouncementService.GetAnnouncementsAsync(currentUser.CurrentBuildingId);
            _pagination.Initialize(comunicados);
        }

        private void OnSearch(ChangeEventArgs e)
        {
            _searchTerm = e.Value?.ToString() ?? string.Empty;
            _pagination.Search(_searchTerm);
        }

        private void ChangePageSize(int newSize)
        {
            _pageSize = newSize;
            _pagination.ChangePageSize(newSize);
        }

        private async Task AbrirNuevo()
        {
            _form = new Announcement
            {
                IdBuilding = currentUser.CurrentBuildingId,
                CreatedBy = currentUser.IdUser,
                Alcance = AnnouncementScope.Publico,
                IdCategoria = _categorias.FirstOrDefault()?.Value ?? 0
            };
            _unidadesSeleccionadas.Clear();
            _resultado = null;
            _errorModal = null;
            await _nuevoModal.ShowAsync();
        }

        private void ToggleUnidad(Guid idGroupUnit, bool marcado)
        {
            if (marcado) _unidadesSeleccionadas.Add(idGroupUnit);
            else _unidadesSeleccionadas.Remove(idGroupUnit);
        }

        // Publicar manda mensajes reales (o Simulados) a gente de verdad -- pasa
        // por confirmación en vez de disparar directo, mismo patrón que el resto
        // de la app usa para acciones irreversibles (ConfirmationUtil, ver
        // Classes/Utilities.cs).
        private async Task ConfirmarPublicar()
        {
            if (string.IsNullOrWhiteSpace(_form.Titulo) || string.IsNullOrWhiteSpace(_form.Cuerpo))
            {
                // El modal sigue abierto acá -- el mensaje va adentro (_errorModal), no en
                // _resultado (quedaría tapado por el backdrop del modal).
                _errorModal = "Título y Cuerpo son obligatorios.";
                return;
            }

            await _util.ExecuteWithConfirmation(
                PublicarAsync,
                "publicar este comunicado",
                _confirmationModal,
                "¿Publicar este comunicado? Se va a mandar por WhatsApp (y por correo, si lo marcaste) a todos los destinatarios del alcance elegido.",
                "warning");
        }

        private async Task OnConfirmationResult(bool confirmed) => await _util.OnConfirmationResult(confirmed);

        private async Task PublicarAsync()
        {
            _publicando = true;
            StateHasChanged();

            try
            {
                var resultado = await AnnouncementService.PublicarAnnouncementAsync(_form, _unidadesSeleccionadas.ToList());

                if (resultado.Exito)
                {
                    _resultadoOk = true;
                    _resultado = $"Comunicado publicado a {resultado.TotalRecipients} destinatario(s) -- " +
                        $"WhatsApp: {resultado.EnviadosWhatsApp} enviados, {resultado.SimuladosWhatsApp} simulados, {resultado.FallidosWhatsApp} fallidos" +
                        (_form.EnviarPorCorreo ? $"; Correo: {resultado.EnviadosCorreo} enviados, {resultado.FallidosCorreo} fallidos." : ".");
                    await _nuevoModal.HideAsync();
                    await CargarAnnouncementsAsync();
                }
                else
                {
                    _errorModal = resultado.Mensaje;
                }
            }
            finally
            {
                _publicando = false;
                StateHasChanged();
            }
        }

        private async Task VerDetalle(Announcement comunicado)
        {
            _comunicadoSeleccionado = comunicado;
            _destinatarios = await AnnouncementService.GetRecipientsAsync(comunicado.IdAnnouncement);
            await _detalleModal.ShowAsync();
        }

        private string DescripcionAlcance(Announcement comunicado) => comunicado.Alcance switch
        {
            AnnouncementScope.Publico => "Público",
            AnnouncementScope.Reservado => $"Reservado ({comunicado.RolReservado})",
            AnnouncementScope.Privado => "Privado",
            _ => comunicado.Alcance.ToString()
        };

        private static string EtiquetaEstadoWhatsApp(WhatsAppDeliveryStatus estado) => estado switch
        {
            WhatsAppDeliveryStatus.Enviado => "✅ Enviado",
            WhatsAppDeliveryStatus.Simulado => "🧪 Simulado",
            WhatsAppDeliveryStatus.Fallido => "❌ Falló",
            _ => "-- No aplica --"
        };

        private static string EtiquetaEstadoCorreo(EmailDeliveryStatus estado) => estado switch
        {
            EmailDeliveryStatus.Enviado => "✅ Enviado",
            EmailDeliveryStatus.Fallido => "❌ Falló",
            _ => "-- No aplica --"
        };
    }
}
