// <autogenerated />
#nullable enable
using BlazorBootstrap;
using Microsoft.AspNetCore.Components;
using SpiderHood.Components.Pages.Components;
using SpiderHood.Models;
using SpiderHood.Utilities;

namespace SpiderHood.Components.Pages.CommunicationPages
{
    public partial class Comunicados
    {
        private bool _loading = true;
        private bool _canPublicar;
        private UserSession currentUser = new();

        private ComunicadoPagination _pagination = new();
        private string _searchTerm = string.Empty;
        private int _pageSize = 25;

        private int _idCategoriaComunicado;
        private List<Parameter> _categorias = new();
        private List<UnitView> _unidades = new();
        private HashSet<Guid> _unidadesSeleccionadas = new();

        private Comunicado _form = new();
        private bool _publicando;
        private string? _resultado;
        private bool _resultadoOk;

        private List<ComunicadoDestinatario> _destinatarios = new();

        private Modal _nuevoModal = null!;
        private Modal _detalleModal = null!;
        private ConfirmationModal? _confirmationModal;
        private readonly ConfirmationUtil _util = new();

        protected override async Task OnInitializedAsync()
        {
            currentUser = await AuthService.GetCurrentUserAsync() ?? new UserSession();
            _canPublicar = await PermissionService.HasPermissionAsync(currentUser, "create_announcements");

            if (_canPublicar && currentUser.CurrentBuildingId != Guid.Empty)
            {
                await ParameterService.LoadParametersAsync(currentUser.CurrentBuildingId);

                // El grupo "Categoría Comunicado" lo crea el script de la migración con
                // IdParent=0 -- su IdTabla real lo asigna SQL Server (IDENTITY), así que
                // se resuelve acá por ShortDescription en vez de asumir un número fijo
                // (a diferencia de grupos viejos como "Tipo Edificio", que sí quedaron
                // hardcodeados en otras pantallas porque ya existían de antes).
                _idCategoriaComunicado = ParameterService.ListParameters
                    .FirstOrDefault(p => p.IdParent == 0 && p.ShortDescription == "Categoría Comunicado")?.IdTabla ?? 0;
                _categorias = ParameterService.ListParameters
                    .Where(p => p.IdParent == _idCategoriaComunicado)
                    .OrderBy(p => p.Sort)
                    .ToList();

                _unidades = await BuildingService.GetGroupUnitsByTypeAsync(currentUser.CurrentBuildingId, 1);

                await CargarComunicadosAsync();
            }

            _loading = false;
        }

        private async Task CargarComunicadosAsync()
        {
            var comunicados = await ComunicadoService.GetComunicadosAsync(currentUser.CurrentBuildingId);
            _pagination.Initialize(comunicados);
        }

        private void OnSearch(ChangeEventArgs e)
        {
            _searchTerm = e.Value?.ToString() ?? string.Empty;
            _pagination.Search(_searchTerm);
        }

        private void ChangePageSize(int newSize)
        {
            _pageSize = newSize;
            _pagination.ChangePageSize(newSize);
        }

        private async Task AbrirNuevo()
        {
            _form = new Comunicado
            {
                IdBuilding = currentUser.CurrentBuildingId,
                CreatedBy = currentUser.IdUser,
                Alcance = AlcanceComunicado.Publico,
                IdCategoria = _categorias.FirstOrDefault()?.Value ?? 0
            };
            _unidadesSeleccionadas.Clear();
            _resultado = null;
            await _nuevoModal.ShowAsync();
        }

        private void ToggleUnidad(Guid idGroupUnit, bool marcado)
        {
            if (marcado) _unidadesSeleccionadas.Add(idGroupUnit);
            else _unidadesSeleccionadas.Remove(idGroupUnit);
        }

        // Publicar manda mensajes reales (o Simulados) a gente de verdad -- pasa
        // por confirmación en vez de disparar directo, mismo patrón que el resto
        // de la app usa para acciones irreversibles (ConfirmationUtil, ver
        // Classes/Utilities.cs).
        private async Task ConfirmarPublicar()
        {
            if (string.IsNullOrWhiteSpace(_form.Titulo) || string.IsNullOrWhiteSpace(_form.Cuerpo))
            {
                _resultado = "Título y Cuerpo son obligatorios.";
                _resultadoOk = false;
                return;
            }

            await _util.ExecuteWithConfirmation(
                PublicarAsync,
                "publicar este comunicado",
                _confirmationModal,
                "¿Publicar este comunicado? Se va a mandar por WhatsApp (y por correo, si lo marcaste) a todos los destinatarios del alcance elegido.",
                "warning");
        }

        private async Task OnConfirmationResult(bool confirmed) => await _util.OnConfirmationResult(confirmed);

        private async Task PublicarAsync()
        {
            _publicando = true;
            StateHasChanged();

            try
            {
                var resultado = await ComunicadoService.PublicarComunicadoAsync(_form, _unidadesSeleccionadas.ToList());
                _resultadoOk = resultado.Exito;
                _resultado = resultado.Exito
                    ? $"Comunicado publicado a {resultado.TotalDestinatarios} destinatario(s) -- " +
                      $"WhatsApp: {resultado.EnviadosWhatsApp} enviados, {resultado.SimuladosWhatsApp} simulados, {resultado.FallidosWhatsApp} fallidos" +
                      (_form.EnviarPorCorreo ? $"; Correo: {resultado.EnviadosCorreo} enviados, {resultado.FallidosCorreo} fallidos." : ".")
                    : resultado.Mensaje;

                if (resultado.Exito)
                {
                    await _nuevoModal.HideAsync();
                    await CargarComunicadosAsync();
                }
            }
            finally
            {
                _publicando = false;
                StateHasChanged();
            }
        }

        private async Task VerDetalle(Comunicado comunicado)
        {
            _destinatarios = await ComunicadoService.GetDestinatariosAsync(comunicado.IdComunicado);
            await _detalleModal.ShowAsync();
        }

        private string DescripcionAlcance(Comunicado comunicado) => comunicado.Alcance switch
        {
            AlcanceComunicado.Publico => "Público",
            AlcanceComunicado.Reservado => $"Reservado ({comunicado.RolReservado})",
            AlcanceComunicado.Privado => "Privado",
            _ => comunicado.Alcance.ToString()
        };

        private static string EtiquetaEstadoWhatsApp(EstadoEnvioWhatsApp estado) => estado switch
        {
            EstadoEnvioWhatsApp.Enviado => "✅ Enviado",
            EstadoEnvioWhatsApp.Simulado => "🧪 Simulado",
            EstadoEnvioWhatsApp.Fallido => "❌ Falló",
            _ => "-- No aplica --"
        };

        private static string EtiquetaEstadoCorreo(EstadoEnvioCorreo estado) => estado switch
        {
            EstadoEnvioCorreo.Enviado => "✅ Enviado",
            EstadoEnvioCorreo.Fallido => "❌ Falló",
            _ => "-- No aplica --"
        };
    }
}
