// <autogenerated />
using SpiderHood.Models;

namespace SpiderHood.Components.Pages.ResidentPages
{
    public partial class MyAnnouncements
    {
        private bool _loading = true;
        private List<Announcement> _comunicados = new();
        private int _idCategoriaAnnouncement;

        protected override async Task OnInitializedAsync()
        {
            var currentUser = await AuthService.GetCurrentUserAsync();
            if (currentUser != null && currentUser.CurrentBuildingId != Guid.Empty)
            {
                await ParameterService.LoadParametersAsync(currentUser.CurrentBuildingId);
                _idCategoriaAnnouncement = ParameterService.ListParameters
                    .FirstOrDefault(p => p.IdParent == 0 && p.ShortDescription == "Categoría Comunicado")?.IdTabla ?? 0;

                var idGroupUnit = await AuthService.GetCurrentUnitIdAsync();
                _comunicados = await AnnouncementService.GetAnnouncementsParaUsuarioAsync(
                    currentUser.CurrentBuildingId, currentUser.Role, idGroupUnit);
            }

            _loading = false;
        }
    }
}
