// <autogenerated />
using BlazorBootstrap;
using Microsoft.AspNetCore.Components;
using Microsoft.JSInterop;
using SpiderHood.Models;

namespace SpiderHood.Components.Pages.BuildingPages
{
    public partial class BuildingConfig
    {
        [Parameter]
        public Guid IdBuilding { get; set; }

        [Inject]
        public Services.ICategoryService CategoryService { get; set; } = default!;
        [Inject]
        public Services.IBuildingService BuildingService { get; set; } = default!;
        [Inject]
        public Services.IBankAccountService BankAccountService { get; set; } = default!;
        [Inject]
        public Services.IAreaComunService AreaComunService { get; set; } = default!;

        private List<Building> Buildings = new();
        private Building SelectedBuilding = null;
        private BankAccount _editingBankAccout = new();

        // Mismo wrapper que en BuildingPage -- BankAccount.Status es un int (no bool),
        // Convención 1=Activo/0=Inactivo.
        private bool BankAccountIsActive
        {
            get => _editingBankAccout.Status == 1;
            set => _editingBankAccout.Status = value ? 1 : 0;
        }

        private Exoneration _Exoneration = new();
        private IReadOnlyList<Models.Parameter> filteredParameters = new List<Models.Parameter>();
        private List<Models.Category> filteredCategory = new();
        private List<Models.UnitView> filteredUnits = new();

        private string ActiveTab = "currency";
        private string _editingSection = "";
        private BuildingConfiguration _configurationBackup = new();
        private bool _isEditingBanckAccount = false;

        private Building _quickConfigBuilding = null;
        private Guid? _sourceBuildingId = null;
        private bool _copyCurrency = true;
        private bool _copyPayments = true;
        private bool _copyFines = true;
        private bool _copyContacts = true;
        private bool _copyAll = true;

        private Modal _quickConfigModal = null!;
        private Modal _bankAccount = null!;
        private Modal _exoneration = null!;
        private Modal _areaComunModal = null!;

        private List<AreaComun> _areasComunes = new();
        private bool _loadingAreasComunes = true;
        private AreaComun _editingAreaComun = new();

        // Se muestra DENTRO del modal (no en el cuerpo de la página, que queda tapado
        // por el backdrop mientras el modal está abierto -- feedback del usuario
        // 2026-09-12: "el mensaje sale por atrás, no se ve"). string.Empty = sin error --
        // este archivo no tiene #nullable enable (es grande y preexistente, no vale la
        // pena habilitarlo sólo por este campo), así que se evita "string?" acá.
        private string _errorAreaComun = string.Empty;

        private string Moneda(decimal valor) => valor.FormatoMoneda(SelectedBuilding?.Configuration.Currency);

        private List<string> _paymentMethods = new();
        private List<Currency> _currencies = new()
        {
            new Currency { Code = "PEN", Symbol = "S/", Name = "Soles" },
            new Currency { Code = "USD", Symbol = "$", Name = "Dólares" },
            new Currency { Code = "EUR", Symbol = "€", Name = "Euros" }
        };

        private UserSession currentUser = new();
        private bool _canEditBuilding;

        // Mismo patrón que IncidentDetail.OnParametersSetAsync (esta sesión, otro bug ya
        // corregido): esta página tiene ruta /buildings/{IdBuilding:guid}/config -- navegar
        // de un edificio a otro (p.ej. desde el listado, click en el ícono de otro edificio)
        // reusa la MISMA instancia del componente porque matchea el mismo template de ruta,
        // así que OnInitializedAsync sólo correría una vez. OnParametersSetAsync sí se
        // dispara en cada cambio de parámetro de ruta -- comparamos contra el último
        // IdBuilding cargado para no recargar de más en cada render.
        private Guid _loadedId = Guid.Empty;

        protected override async Task OnParametersSetAsync()
        {
            if (IdBuilding != _loadedId)
            {
                _loadedId = IdBuilding;
                await LoadAsync(IdBuilding);
            }
        }

        private async Task LoadAsync(Guid idBuilding)
        {
            currentUser = await AuthService.GetCurrentUserAsync();
            if (currentUser == null) return;

            _canEditBuilding = await PermissionService.HasPermissionAsync(currentUser, "edit_building");

            Buildings = currentUser.Buildings!.Where(c => c.Role == currentUser.Role).Select(ub => ub.Building).ToList()!;

            var building = Buildings.FirstOrDefault(b => b.IdBuilding == idBuilding);
            if (building == null)
            {
                // No pertenece a este usuario (o no existe) -- volver al listado en vez de
                // mostrar una página de configuración sin edificio.
                Navigation.NavigateTo("/buildings");
                return;
            }

            SelectedBuilding = null;
            StateHasChanged();

            await ParameterService.LoadParametersAsync(idBuilding);
            filteredParameters = ParameterService.ListParameters;

            filteredCategory = await CategoryService.GetCategoriesAsync(idBuilding);
            filteredUnits = await BuildingService.GetGroupUnitsByTypeAsync(idBuilding, 1);

            _paymentMethods = filteredParameters
                .Where(c => c.IdParent == 16)
                .Select(c => c.ShortDescription)
                .ToList();

            building.Configuration = await BuildingService.GetConfigurationAsync(idBuilding);
            SelectedBuilding = building;
            _editingSection = "";
            ActiveTab = "currency";

            _loadingAreasComunes = true;
            _areasComunes = await AreaComunService.GetAreaComunesAsync(idBuilding);
            _loadingAreasComunes = false;
        }

        private void ShowAddAreaComunModal()
        {
            if (!_canEditBuilding) return;
            _editingAreaComun = new AreaComun { IdBuilding = SelectedBuilding!.IdBuilding, Activo = true };
            _errorAreaComun = string.Empty;
            _areaComunModal.ShowAsync();
        }

        private void ShowEditAreaComunModal(AreaComun area)
        {
            if (!_canEditBuilding) return;
            _editingAreaComun = area.Clone();
            _errorAreaComun = string.Empty;
            _areaComunModal.ShowAsync();
        }

        private async Task SaveAreaComun()
        {
            if (!_canEditBuilding || SelectedBuilding == null) return;

            if (string.IsNullOrWhiteSpace(_editingAreaComun.Nombre))
            {
                _errorAreaComun = "El nombre es obligatorio.";
                return;
            }

            if (_editingAreaComun.IdAreaComun == Guid.Empty)
            {
                _editingAreaComun.CreatedBy = currentUser.IdUser;
                var creada = await AreaComunService.CrearAsync(_editingAreaComun);
                _areasComunes.Add(creada);
            }
            else
            {
                await AreaComunService.ActualizarAsync(_editingAreaComun);
                var index = _areasComunes.FindIndex(a => a.IdAreaComun == _editingAreaComun.IdAreaComun);
                if (index >= 0) _areasComunes[index] = _editingAreaComun;
            }

            await _areaComunModal.HideAsync();
        }

        private async Task CloseBankModal()
        {
            await _bankAccount.HideAsync();
        }

        private async Task CloseExonerationModal()
        {
            await _exoneration.HideAsync();
        }

        private void StartEditSection(string section)
        {
            if (!_canEditBuilding) return;
            if (SelectedBuilding != null)
            {
                _configurationBackup = SelectedBuilding.Configuration.Clone();
                _editingSection = section;
            }
        }

        private void CancelEdit()
        {
            if (SelectedBuilding != null && !string.IsNullOrEmpty(_editingSection))
            {
                SelectedBuilding.Configuration = _configurationBackup.Clone();
            }
            _editingSection = "";
        }

        private async Task SaveSection(string section)
        {
            if (!_canEditBuilding) return;
            try
            {
                var interno = SelectedBuilding!.Configuration;

                if (interno.IdBuildingConfiguration == Guid.Empty)
                {
                    interno.IdBuildingConfiguration = Guid.NewGuid();
                    interno.IdBuilding = SelectedBuilding.IdBuilding;
                    await BuildingService.CreateConfigurationAsync(interno);
                }

                switch (section)
                {
                    case "payments":
                        break;

                    case "currency":
                        if (interno.BankAccounts.Count > 0)
                        {
                            foreach (var bankaccount in interno.BankAccounts)
                            {
                                if (bankaccount.IdBankAccount == Guid.Empty)
                                {
                                    bankaccount.IdBankAccount = Guid.NewGuid();
                                    bankaccount.IdBuilding = interno.IdBuilding;

                                    await BankAccountService.AddBankAccount(bankaccount);
                                }
                                else
                                {
                                    await BankAccountService.UpdateBankAccount(bankaccount);
                                }
                            }
                        }
                        break;

                    case "fines":
                        break;

                    case "admin":
                        if (SelectedBuilding.Configuration.AdminContact.IdContact == Guid.Empty)
                        {
                            SelectedBuilding.Configuration.AdminContact.IdContact = Guid.NewGuid();
                            SelectedBuilding.Configuration.AdminContact.IdRelatedEntity = interno.IdBuildingConfiguration;
                            SelectedBuilding.Configuration.AdminContact.TypeContact = 1;
                            await BuildingService.AddContactAsync(SelectedBuilding.Configuration.AdminContact);
                        }
                        else
                        {
                            await BuildingService.UpdateContactAsync(SelectedBuilding.Configuration.AdminContact);
                        }
                        break;

                    case "realty":
                        if (SelectedBuilding.Configuration.RealEstateCompany.IdContact == Guid.Empty)
                        {
                            SelectedBuilding.Configuration.RealEstateCompany.IdContact = Guid.NewGuid();
                            SelectedBuilding.Configuration.RealEstateCompany.IdRelatedEntity = interno.IdBuildingConfiguration;
                            SelectedBuilding.Configuration.RealEstateCompany.TypeContact = 2;
                            await BuildingService.AddContactAsync(SelectedBuilding.Configuration.RealEstateCompany);
                        }
                        else
                        {
                            await BuildingService.UpdateContactAsync(SelectedBuilding.Configuration.RealEstateCompany);
                        }
                        break;

                    case "maintenance":
                        if (SelectedBuilding.Configuration.MaintenanceCompany.IdContact == Guid.Empty)
                        {
                            SelectedBuilding.Configuration.MaintenanceCompany.IdContact = Guid.NewGuid();
                            SelectedBuilding.Configuration.MaintenanceCompany.IdRelatedEntity = interno.IdBuildingConfiguration;
                            SelectedBuilding.Configuration.MaintenanceCompany.TypeContact = 3;
                            await BuildingService.AddContactAsync(SelectedBuilding.Configuration.MaintenanceCompany);
                        }
                        else
                        {
                            await BuildingService.UpdateContactAsync(SelectedBuilding.Configuration.MaintenanceCompany);
                        }
                        break;

                    case "category":
                        break;

                    case "exception":
                        if (interno.Exonerations.Count > 0)
                        {
                            foreach (var _exception in interno.Exonerations)
                            {
                                if (_exception.IdExoneration == Guid.Empty)
                                {
                                    _exception.IdExoneration = Guid.NewGuid();
                                    _exception.IdBuilding = interno.IdBuilding;

                                    await BuildingService.AddExonerationAsync(_exception);
                                }
                                else
                                {
                                    if (_exception.IsDeleted)
                                        await BuildingService.DeleteExonerationAsync(_exception);
                                }
                            }
                        }
                        break;
                }

                await BuildingService.UpdateConfigurationAsync(SelectedBuilding.Configuration);

                await BuildingService.UpdateExpenseApprovalThresholdAsync(
                    SelectedBuilding.Configuration.IdBuildingConfiguration,
                    SelectedBuilding.Configuration.ExpenseApprovalThreshold);

                if (ParameterService.CurrentBuilding != null &&
                    ParameterService.CurrentBuilding.IdBuilding == SelectedBuilding.IdBuilding)
                {
                    ParameterService.CurrentBuilding.Configuration = SelectedBuilding.Configuration.Clone();
                }

                _editingSection = "";
                StateHasChanged();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error al guardar: {ex.Message}");
                await JSRuntime.InvokeVoidAsync("alert", $"No se pudo guardar: {ex.Message}");
            }
        }

        private async Task SaveConfiguration()
        {
            try
            {
                await Task.Delay(500);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error al guardar configuración: {ex.Message}");
            }
        }

        private void AddBankAccount()
        {
            if (SelectedBuilding != null)
            {
                _editingBankAccout = new BankAccount { Status = 1 };
                _isEditingBanckAccount = false;
                _bankAccount.ShowAsync();
            }
        }

        private void ShowAddExceptionModal()
        {
            if (SelectedBuilding != null)
            {
                _exoneration.ShowAsync();
            }
        }

        private void EditBankAccount(int index)
        {
            if (SelectedBuilding != null && index >= 0 && index < SelectedBuilding.Configuration.BankAccounts.Count)
            {
                _editingBankAccout = SelectedBuilding.Configuration.BankAccounts[index];
                _isEditingBanckAccount = true;
            }
            _bankAccount.ShowAsync();
        }

        private void RemoveBankAccount(int index)
        {
            if (SelectedBuilding != null && SelectedBuilding.Configuration.BankAccounts.Count > 1)
            {
                SelectedBuilding.Configuration.BankAccounts.RemoveAt(index);
            }
        }

        private void RemoveException(Exoneration item)
        {
            item.IsDeleted = true;
            StateHasChanged();
        }

        private void TogglePaymentMethod(string method)
        {
            if (SelectedBuilding != null)
            {
                if (SelectedBuilding.Configuration.PaymentMethods.Contains(method))
                {
                    SelectedBuilding.Configuration.PaymentMethods.Remove(method);
                }
                else
                {
                    SelectedBuilding.Configuration.PaymentMethods.Add(method);
                }
            }
        }

        private async Task SaveBankAccout()
        {
            try
            {
                if (!_isEditingBanckAccount)
                {
                    SelectedBuilding!.Configuration.BankAccounts.Add(_editingBankAccout);
                    _editingBankAccout = new BankAccount();
                }
                await _bankAccount.HideAsync();
                StateHasChanged();
                _isEditingBanckAccount = false;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error al guardar cuenta: {ex.Message}");
            }
        }

        private async Task SaveExoneration()
        {
            try
            {
                SelectedBuilding!.Configuration.Exonerations.Add(_Exoneration);
                _Exoneration = new Exoneration();
                await _exoneration.HideAsync();
                StateHasChanged();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error al guardar exoneración: {ex.Message}");
            }
        }

        private async Task ShowQuickConfig(Building building)
        {
            _quickConfigBuilding = building;
            _sourceBuildingId = null;
            _copyCurrency = _copyPayments = _copyFines = _copyContacts = _copyAll = true;
            await _quickConfigModal.ShowAsync();
        }

        private async Task ApplyQuickConfig()
        {
            if (_quickConfigBuilding != null && _sourceBuildingId.HasValue)
            {
                var sourceBuilding = Buildings.FirstOrDefault(b => b.IdBuilding == _sourceBuildingId.Value);
                if (sourceBuilding != null)
                {
                    if (_copyCurrency)
                    {
                        _quickConfigBuilding.Configuration.Currency = sourceBuilding.Configuration.Currency;
                        _quickConfigBuilding.Configuration.BankAccounts = sourceBuilding.Configuration.BankAccounts
                            .Select(a =>
                            {
                                var clon = a.Clone();
                                clon.IdBankAccount = Guid.Empty;
                                clon.IdBuilding = Guid.Empty;
                                return clon;
                            }).ToList();
                    }

                    if (_copyPayments)
                    {
                        _quickConfigBuilding.Configuration.PaymentMethods = new List<string>(sourceBuilding.Configuration.PaymentMethods);
                        _quickConfigBuilding.Configuration.PaymentPeriod = sourceBuilding.Configuration.PaymentPeriod;
                        _quickConfigBuilding.Configuration.DueDay = sourceBuilding.Configuration.DueDay;
                    }

                    if (_copyFines)
                    {
                        _quickConfigBuilding.Configuration.FineAmount = sourceBuilding.Configuration.FineAmount;
                        _quickConfigBuilding.Configuration.LateInterestRate = sourceBuilding.Configuration.LateInterestRate;
                        _quickConfigBuilding.Configuration.InvoiceDay = sourceBuilding.Configuration.InvoiceDay;
                    }

                    if (_copyContacts)
                    {
                        _quickConfigBuilding.Configuration.AdminContact = sourceBuilding.Configuration.AdminContact.Clone();
                        _quickConfigBuilding.Configuration.AdminContact.IdContact = Guid.Empty;
                        _quickConfigBuilding.Configuration.AdminContact.IdRelatedEntity = Guid.Empty;

                        _quickConfigBuilding.Configuration.RealEstateCompany = sourceBuilding.Configuration.RealEstateCompany.Clone();
                        _quickConfigBuilding.Configuration.RealEstateCompany.IdContact = Guid.Empty;
                        _quickConfigBuilding.Configuration.RealEstateCompany.IdRelatedEntity = Guid.Empty;

                        _quickConfigBuilding.Configuration.MaintenanceCompany = sourceBuilding.Configuration.MaintenanceCompany.Clone();
                        _quickConfigBuilding.Configuration.MaintenanceCompany.IdContact = Guid.Empty;
                        _quickConfigBuilding.Configuration.MaintenanceCompany.IdRelatedEntity = Guid.Empty;
                    }

                    if (SelectedBuilding?.IdBuilding == _quickConfigBuilding.IdBuilding)
                    {
                        SelectedBuilding = _quickConfigBuilding;
                    }

                    await _quickConfigModal.HideAsync();
                    StateHasChanged();
                }
            }
        }

        private string GetCategoryName(Guid IdSearch)
        {
            var category = filteredCategory.FirstOrDefault(c => c.IdCategory == IdSearch);
            return category?.ShortDescript ?? "Categoría General";
        }

        private string GetGroupUnitName(Guid IdSearch)
        {
            var groupunit = filteredUnits.FirstOrDefault(c => c.IdGroupUnit == IdSearch);
            return groupunit?.UnitNumber ?? "Sin Data";
        }
    }
}
