// <autogenerated />
using BlazorBootstrap;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.JSInterop;
using SpiderHood.Models;

namespace SpiderHood.Components.Pages.BuildingPages
{
    public partial class BuildingPage : IDisposable
    {
        [Inject]
        public Services.IBuildingService BuildingService { get; set; } = default!;

        [Inject]
        public Services.IBuildingBoardService BuildingBoardService { get; set; } = default!;

        private List<Building> Buildings = new();
        private Building SelectedBuilding = null;
        private Building _editingBuilding = new();

        private bool _isEditingBuilding = false;

        // Paginación/búsqueda del listado -- mismo patrón que PeriodPage (Utilities.PaginationClass<T>).
        private Utilities.BuildingPagination _pagination = new();
        private string searchTerm = string.Empty;
        private int pageSize = 25;

        private Modal _buildingModal = null!;
        private Modal _deleteBuildingModal = null!;
        private Building _buildingToDelete = null;
        private string _deleteBuildingConfirmText = "";

        private UserSession currentUser = new();
        private bool _canEditBuilding;
        private bool _canCreateBuilding;

        private string? _buildingLogoDataUri;
        private bool _subiendoLogoEdificio;
        private string? _buildingLogoError;

        // "Efectivo" = lo que se usaría si el campo del Edificio queda vacío (fallback
        // a la Account, Docs/Pendientes-Negocio-Consolidado.md #33) -- sólo para mostrar
        // como placeholder en el Tab "Contacto", nunca se guarda solo -- el usuario sigue
        // pudiendo cargar su propio dato por edificio si lo necesita.
        private (string? AdminName, string? AdminPhone, string? OfficeHours) _effectiveContact;

        // Junta Directiva (Docs/Pendientes-Negocio-Consolidado.md #34) -- Tab 5, sólo
        // visible editando un edificio ya guardado.
        private BuildingBoard? _activeBoard;
        private List<BuildingBoardMemberView> _boardMembers = new();
        private List<UserBuildingRoleAssignment> _eligibleBoardUsers = new();
        private DateOnly _newBoardFechaInicio = DateOnly.FromDateTime(DateTime.Today);
        private Guid? _newMemberIdUser;
        private BoardMemberRole _newMemberCargo = BoardMemberRole.Vocal;
        private string? _newMemberOtroDescripcion;
        // null = todavía no se comprobó (no se seleccionó nadie) -- true = el email del
        // usuario elegido no matchea ningún Owner activo del edificio, se muestra el
        // aviso; false = sí matchea, no hace falta avisar. Nunca bloquea el alta.
        private bool? _newMemberOwnerWarning;
        private string? _boardError;
        private bool _savingBoard;

        protected override async Task OnInitializedAsync()
        {
            // Suscribirse una sola vez -- OnInitializedAsync corre una sola vez por
            // instancia de componente (a diferencia de CargarDatosPagina, que se llama de
            // nuevo después de crear/editar/eliminar un edificio); suscribirse ahí
            // acumularía handlers duplicados en OnPaginationChanged.
            _pagination.OnPaginationChanged += StateHasChanged;

            currentUser = await AuthService.GetCurrentUserAsync();
            if (currentUser == null) return;

            _canEditBuilding = await PermissionService.HasPermissionAsync(currentUser, "edit_building");
            _canCreateBuilding = await PermissionService.HasPermissionAsync(currentUser, "create_building");
        }

        public void Dispose()
        {
            _pagination.OnPaginationChanged -= StateHasChanged;
        }

        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                await InicializarPagina();
                StateHasChanged();
            }
        }

        protected async Task InicializarPagina()
        {
            Console.WriteLine($"🏢 Buildings.OnInitializedAsync - Iniciando");

            try
            {
                await CargarDatosPagina();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"❌ Error en OnInitializedAsync: {ex.Message}");
            }
        }

        private async Task CargarDatosPagina()
        {
            // Cargar edificios del propietario
            Buildings = currentUser!.Buildings!.Where(c => c.Role == currentUser.Role).Select(ub => ub.Building).ToList()!;

            // Sin ningún Building todavía (instalación nueva) Buildings queda vacía --
            // Buildings.First() tiraba InvalidOperationException acá, silenciada por el
            // try/catch de InicializarPagina, y el resto de la carga nunca corría. El
            // markup ya maneja bien Buildings vacía (@if (Buildings.Any())), así que
            // alcanza con no crashear acá.
            if (!Buildings.Any())
            {
                _pagination.Initialize(Buildings);

                // Quien se acaba de registrar desde /register-admin (Administrador
                // global, sin ningún edificio todavía -- ver
                // AuthService.RegisterNewAdministratorAsync) cae acá directo después del
                // autologin. En vez de mostrar la página vacía y esperar a que encuentre
                // el botón "Nuevo Edificio", se le abre el modal de una -- es su único
                // paso pendiente para poder usar el sistema.
                if (_canCreateBuilding)
                    await ShowCreateModal();

                return;
            }

            SelectedBuilding = Buildings.First();
            _pagination.Initialize(Buildings);

            // Necesarios acá sólo para el badge de Tipo de la lista y para el <select>
            // "Tipo" del modal de crear/editar edificio -- la configuración completa
            // (BankAccounts, Exonerations, categorías, unidades, etc.) ya no se carga en
            // esta página, se carga en BuildingConfig al entrar a /buildings/{Id}/config.
            await ParameterService.LoadParametersAsync(SelectedBuilding.IdBuilding);
        }

        private void OnSearch(ChangeEventArgs e)
        {
            searchTerm = e.Value?.ToString() ?? string.Empty;
            _pagination.Search(searchTerm);
        }

        private void ChangePageSize(int newSize)
        {
            pageSize = newSize;
            _pagination.ChangePageSize(pageSize);
        }

        private void GoToConfig(Building building)
        {
            Navigation.NavigateTo($"/buildings/{building.IdBuilding}/config");
        }

        // Docs/Pendientes-Negocio-Migracion.md #6.3 -- sólo SysAdmin (gate repetido acá
        // porque este método es la puerta real: el botón que lo dispara ya está
        // condicionado a currentUser.Role == "SysAdmin" en el markup, pero un método
        // invocable desde @onclick no debe confiar únicamente en que el botón que lo
        // llama esté oculto). Sólo sirve para edificios de PRUEBA vacíos -- ver el
        // comentario en IBuildingService.DeleteBuildingAsync.
        private async Task ShowDeleteBuildingModal(Building building)
        {
            if (currentUser.Role != "SysAdmin") return;

            _buildingToDelete = building;
            _deleteBuildingConfirmText = "";
            await _deleteBuildingModal.ShowAsync();
        }

        private async Task HideDeleteBuildingModal()
        {
            _buildingToDelete = null;
            _deleteBuildingConfirmText = "";
            await _deleteBuildingModal.HideAsync();
        }

        // Requiere escribir el nombre exacto del edificio -- borrar un edificio es
        // mucho más grave que borrar una categoría o unidad (que sólo tienen un modal
        // de "¿Está seguro?"), así que el botón "Eliminar" queda deshabilitado
        // (ver el markup) hasta que el texto matchee exacto.
        private async Task DeleteBuildingConfirmed()
        {
            if (currentUser.Role != "SysAdmin" || _buildingToDelete == null) return;
            if (_deleteBuildingConfirmText != _buildingToDelete.Name) return;

            var building = _buildingToDelete;

            try
            {
                var result = await BuildingService.DeleteBuildingAsync(building);
                if (!result.IsSuccess)
                {
                    await JSRuntime.InvokeVoidAsync("alert", result.ErrorMessage ?? "No se pudo eliminar el edificio");
                    return;
                }

                Buildings.RemoveAll(b => b.IdBuilding == building.IdBuilding);
                _pagination.Initialize(Buildings);

                if (SelectedBuilding?.IdBuilding == building.IdBuilding)
                {
                    SelectedBuilding = Buildings.FirstOrDefault();
                }

                // Mismo motivo que en SaveBuilding: sin esto, el edificio borrado seguía
                // apareciendo en el header/selector del resto de la app (currentUser.Buildings
                // cacheado en la sesión del circuito) hasta un F5.
                await AuthService.RefreshCurrentUserBuildingsAsync();

                await HideDeleteBuildingModal();
                StateHasChanged();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error al eliminar edificio: {ex.Message}");
                await JSRuntime.InvokeVoidAsync("alert", "No se pudo eliminar el edificio");
            }
        }

        private async Task EditBuilding(Building building)
        {
            if (!_canEditBuilding) return;
            _editingBuilding = building.Clone();
            await CargarLogoEdificioAsync();
            _effectiveContact = await BuildingService.GetEffectiveContactAsync(_editingBuilding);
            await CargarJuntaDirectivaAsync();

            // Edificios creados antes del fix del <select> "Tipo" (ver commit del bug de
            // Type) quedaron con Type=0, que no matchea ningún Parameter.Value real (1/2/3
            // -- Familiar/Comercial/Mixto). Sin esto, el <select> del modal no encuentra
            // ninguna <option> que coincida con 0 y el navegador termina mostrando la
            // PRIMERA opción igual (aunque el valor subyacente siga en 0) -- si el usuario
            // no toca el combo porque ya "se ve bien", Guardar nunca dispara el onchange y
            // vuelve a persistir el mismo 0 de siempre. Normalizamos acá al primer valor
            // real para que lo que se ve y lo que se va a guardar sean lo mismo desde que
            // se abre el modal.
            var tiposValidos = ParameterService.ListParameters.Where(p => p.IdParent == 34).Select(p => p.Value).ToHashSet();
            if (!tiposValidos.Contains(_editingBuilding.Type))
            {
                _editingBuilding.Type = ParameterService.ListParameters
                    .Where(p => p.IdParent == 34)
                    .OrderBy(p => p.Value)
                    .Select(p => p.Value)
                    .FirstOrDefault();
            }

            _isEditingBuilding = true;
            await _buildingModal.ShowAsync();
        }

        private async Task ShowCreateModal()
        {
            if (!_canCreateBuilding) return;

            // "Nuevo Edificio" se abre desde 3 lugares -- el auto-open de
            // InicializarPagina para un Administrador recién registrado sin ningún
            // edificio todavía, y los 2 botones "+" de la lista (BuildingPage.razor)
            // -- y cualquiera puede llegar acá antes de que
            // ParameterService.ListParameters se haya cargado alguna vez en este
            // circuito. Sin esto, el <select> de "Tipo" de abajo no tenía ninguna
            // opción para mostrar la primera vez. GET_AllParameters trae "WHERE
            // IdBuilding = @IdBuilding OR IdBuilding IS NULL", así que cualquier Guid
            // sirve para traer los parámetros de Sistema globales (Tipo Edificio,
            // IdParent=34, entre ellos) -- se usa el del edificio ya seleccionado si
            // hay uno, o Guid.Empty si todavía no hay ninguno.
            if (ParameterService.ListParameters.Count == 0)
            {
                await ParameterService.LoadParametersAsync(SelectedBuilding?.IdBuilding ?? Guid.Empty);
            }

            var newBuildingId = Guid.NewGuid();
            _editingBuilding = new Building
            {
                IdBuilding = newBuildingId,
                Number = Buildings.Count + 1,
                IsActive = true,
                // Primer valor real de "Tipo Edificio" (IdParent=34, Sistema global) en vez
                // de dejar el default 0 de int -- 0 no matchea ningún Parameter.Value real,
                // así que sin esto el <select> del modal arranca en un valor que no
                // corresponde a ninguna opción mostrada.
                Type = ParameterService.ListParameters.Where(p => p.IdParent == 34).OrderBy(p => p.Value).FirstOrDefault()?.Value ?? 0,
                // CreateDefaultConfigurationAsync no setea Configuration.IdBuilding (el
                // Guid que recibe no se usa para nada adentro) -- si no se lo asignamos
                // acá, CreateBuildingAsync guardaría la config con IdBuilding en blanco,
                // sin relación real al edificio que se acaba de crear.
                Configuration = BuildingService.CreateDefaultConfigurationAsync(newBuildingId)
            };
            _editingBuilding.Configuration.IdBuilding = newBuildingId;
            _isEditingBuilding = false;
            _buildingLogoDataUri = null;
            // Un edificio recién creado todavía no tiene IdAccount asignado -- sin dato
            // de Account contra el cual resolver el fallback, así que no hay nada que
            // mostrar como placeholder todavía (se calcula recién al editarlo, ver
            // EditBuilding).
            _effectiveContact = default;
            await _buildingModal.ShowAsync();
        }

        private async Task CargarLogoEdificioAsync()
        {
            _buildingLogoError = null;
            var bytes = await BuildingService.GetLogoBytesAsync(_editingBuilding);
            var contentType = string.IsNullOrEmpty(_editingBuilding.LogoContentType)
                ? "image/png"
                : _editingBuilding.LogoContentType;
            _buildingLogoDataUri = bytes == null ? null : $"data:{contentType};base64,{Convert.ToBase64String(bytes)}";
        }

        private async Task SubirLogoEdificioAsync(InputFileChangeEventArgs e)
        {
            if (!_canEditBuilding) return;
            _buildingLogoError = null;
            var file = e.File;
            if (file is null) return;

            _subiendoLogoEdificio = true;
            try
            {
                // Techo de transporte por encima del límite real de negocio (2 MB,
                // validado adentro de IBuildingService.UploadLogoAsync) -- mismo
                // criterio que IncidentDetail.razor.SubirAdjunto/Settings.razor.SubirLogoAsync.
                using var stream = file.OpenReadStream(maxAllowedSize: 5 * 1024 * 1024);
                using var memoryStream = new MemoryStream();
                await stream.CopyToAsync(memoryStream);

                await BuildingService.UploadLogoAsync(_editingBuilding.IdBuilding, file.Name, file.ContentType, memoryStream.ToArray());
                await CargarLogoEdificioAsync();
            }
            catch (ArgumentException ex)
            {
                _buildingLogoError = ex.Message;
            }
            catch (Exception ex)
            {
                _buildingLogoError = $"No se pudo subir el logo: {ex.Message}";
            }
            finally
            {
                _subiendoLogoEdificio = false;
            }
        }

        private async Task CargarJuntaDirectivaAsync()
        {
            _boardError = null;
            _activeBoard = await BuildingBoardService.GetActiveBoardAsync(_editingBuilding.IdBuilding);
            _boardMembers = _activeBoard is null
                ? new List<BuildingBoardMemberView>()
                : await BuildingBoardService.GetMembersAsync(_activeBoard.IdBuildingBoard);
            _eligibleBoardUsers = await BuildingBoardService.GetEligibleUsersAsync(_editingBuilding.IdBuilding);
            _newBoardFechaInicio = DateOnly.FromDateTime(DateTime.Today);
            _newMemberIdUser = null;
            _newMemberOwnerWarning = null;
        }

        // "Constituir" = crear una Junta nueva -- si ya había una activa, INS_BuildingBoard
        // la cierra sola (ver comentario en el script SQL), así que este mismo botón sirve
        // tanto para la primera Junta de un edificio como para "Cerrar esta Junta y
        // constituir una nueva".
        private async Task ConstituirNuevaJuntaAsync()
        {
            if (!_canEditBuilding) return;
            _boardError = null;
            _savingBoard = true;
            try
            {
                await BuildingBoardService.CreateBoardAsync(
                    _editingBuilding.IdBuilding,
                    _newBoardFechaInicio.ToDateTime(TimeOnly.MinValue),
                    currentUser.IdUser);
                await CargarJuntaDirectivaAsync();
            }
            catch (Exception ex)
            {
                _boardError = $"No se pudo constituir la Junta: {ex.Message}";
            }
            finally
            {
                _savingBoard = false;
            }
        }

        // Dispara la advertencia blanda (Docs/Pendientes-Negocio-Consolidado.md #34) al
        // elegir un usuario para un cargo -- nunca bloquea, sólo informa.
        private async Task OnMemberUserSelectedAsync(ChangeEventArgs e)
        {
            _newMemberIdUser = Guid.TryParse(e.Value?.ToString(), out var id) ? id : null;
            _newMemberOwnerWarning = _newMemberIdUser is Guid idUser
                ? !await BuildingBoardService.CheckOwnerWarningAsync(_editingBuilding.IdBuilding, idUser)
                : null;
        }

        private async Task AgregarMiembroJuntaAsync()
        {
            if (!_canEditBuilding || _activeBoard is null || _newMemberIdUser is not Guid idUser) return;
            _boardError = null;
            _savingBoard = true;
            try
            {
                await BuildingBoardService.AddMemberAsync(_activeBoard.IdBuildingBoard, idUser, _newMemberCargo, _newMemberOtroDescripcion);
                _newMemberIdUser = null;
                _newMemberOtroDescripcion = null;
                _newMemberOwnerWarning = null;
                _boardMembers = await BuildingBoardService.GetMembersAsync(_activeBoard.IdBuildingBoard);
            }
            catch (Exception ex)
            {
                _boardError = $"No se pudo agregar el miembro: {ex.Message}";
            }
            finally
            {
                _savingBoard = false;
            }
        }

        private async Task EliminarMiembroJuntaAsync(Guid idBuildingBoardMember)
        {
            if (!_canEditBuilding || _activeBoard is null) return;
            _boardError = null;
            try
            {
                await BuildingBoardService.RemoveMemberAsync(idBuildingBoardMember);
                _boardMembers = await BuildingBoardService.GetMembersAsync(_activeBoard.IdBuildingBoard);
            }
            catch (Exception ex)
            {
                _boardError = $"No se pudo quitar el miembro: {ex.Message}";
            }
        }

        private async Task SaveBuilding()
        {
            if (_isEditingBuilding ? !_canEditBuilding : !_canCreateBuilding) return;
            try
            {
                if (_isEditingBuilding)
                {
                    var result = await BuildingService.UpdateBuildingAsync(_editingBuilding);
                    if (!result.IsSuccess)
                    {
                        await JSRuntime.InvokeVoidAsync("alert", result.ErrorMessage ?? "No se pudo actualizar el edificio");
                        return;
                    }

                    var index = Buildings.FindIndex(b => b.IdBuilding == _editingBuilding.IdBuilding);
                    if (index >= 0)
                    {
                        Buildings[index] = _editingBuilding.Clone();
                    }
                    _pagination.Initialize(Buildings);

                    // Sin esto la sesión en memoria seguía con el Name/IsTemplate viejo
                    // (header, /select-building, etc.) hasta un F5 -- ver
                    // AuthService.RefreshCurrentUserBuildingsAsync.
                    await AuthService.RefreshCurrentUserBuildingsAsync();
                }
                else
                {
                    // Sin esto, crear un edificio sólo lo agregaba a esta lista en
                    // memoria -- se perdía apenas se recargaba la página, porque nunca
                    // se guardó nada en la BD (ni el Building, ni su
                    // BuildingConfiguration, ni la asociación que hace que quien lo creó
                    // lo vea en su lista de edificios).
                    var result = await BuildingService.CreateBuildingAsync(_editingBuilding, currentUser.IdUser, currentUser.Role);
                    if (!result.IsSuccess)
                    {
                        await JSRuntime.InvokeVoidAsync("alert", result.ErrorMessage ?? "No se pudo crear el edificio");
                        return;
                    }

                    Buildings.Add(_editingBuilding.Clone());
                    _pagination.Initialize(Buildings);

                    // Refresca Buildings/Roles de la sesión en memoria y notifica -- sin
                    // esto el edificio nuevo sólo se veía en esta lista local (que además
                    // se pierde al volver a entrar a esta página, porque CargarDatosPagina
                    // relee currentUser.Buildings, la sesión cacheada del circuito). El
                    // header y el resto de páginas quedaban sin verlo hasta un F5 real
                    // (que fuerza un circuito nuevo). Ver
                    // AuthService.RefreshCurrentUserBuildingsAsync.
                    await AuthService.RefreshCurrentUserBuildingsAsync();
                }

                // Si estamos editando el edificio seleccionado, actualizarlo
                if (SelectedBuilding?.IdBuilding == _editingBuilding.IdBuilding)
                {
                    SelectedBuilding = _editingBuilding.Clone();
                }

                await _buildingModal.HideAsync();
                StateHasChanged();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error al guardar edificio: {ex.Message}");
            }
        }

        private int activeTab = 1;

        // Tab 5 "Junta Directiva" sólo aplica a un edificio ya guardado (necesita un
        // IdBuilding real para la FK de BuildingBoard) -- un edificio nuevo se queda
        // en 4 tabs hasta que se crea.
        private int MaxTab => _isEditingBuilding ? 5 : 4;

        private void NextTab()
        {
            if (activeTab < MaxTab) activeTab++;
        }

        private void PreviousTab()
        {
            if (activeTab > 1) activeTab--;
        }
    }
}
