// <autogenerated />
using BlazorBootstrap;
using Microsoft.AspNetCore.Components;
using SpiderHood.Models;

namespace SpiderHood.Components.Pages.BuildingPages
{
    public partial class BuildingPage
    {

        [Inject]
        public Services.ICategoryService CategoryService { get; set; } = default!;
        [Inject]
        public Services.IBuildingService BuildingService { get; set; } = default!;
        [Inject]
        public Services.IBankAccountService BankAccountService { get; set; } = default!;

        private List<Building> Buildings = new();
        private Building? SelectedBuilding = null;
        private Building _editingBuilding = new();
        private Building? _quickConfigBuilding = null;
        private BankAccount _editingBankAccout = new();
        private Exoneration _Exoneration = new();
        private IReadOnlyList<Models.Parameter>? filteredParameters;
        private List<Models.Category> filteredCategory = new();
        private List<Models.UnitView> filteredUnits = new();

        private string _editingSection = "";
        private BuildingConfiguration _configurationBackup = new();
        private bool _isEditingBuilding = false;
        private bool _isEditingBanckAccount = false;
        private Guid? _sourceBuildingId = null;
        private bool _copyCurrency = true;
        private bool _copyPayments = true;
        private bool _copyFines = true;
        private bool _copyContacts = true;
        private bool _copyAll = true;

        private Modal _buildingModal = null!;
        private Modal _quickConfigModal = null!;
        private Modal _bankAccount = null!;
        private Modal _exoneration = null!;

        private List<string> _paymentMethods = new();// { "Transferencia Bancaria", "Pago en Efectivo", "Tarjeta de Crédito", "Cheque" };
        private List<Currency> _currencies = new()
    {
        new Currency { Code = "PEN", Symbol = "S/", Name = "Soles" },
        new Currency { Code = "USD", Symbol = "$", Name = "Dólares" },
        new Currency { Code = "EUR", Symbol = "€", Name = "Euros" }
    };

        private bool _isLoading = true;
        private Guid IdBuilding = Guid.Empty;
        UserSession? currentUser = new();
        private bool _loaded = false;

        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                await InicializarPagina();
                _loaded = true;
                StateHasChanged();
            }
        }
        
        protected async Task InicializarPagina()
        {
            // Verificar si ya está inicializado o cancelado
            Console.WriteLine($"🏢 Buildings.OnInitializedAsync - Iniciando");

            try
            {
                // 1. VERIFICAR USUARIO AUTENTICADO
                currentUser = await VerificarUsuarioAutenticado();
                if (currentUser == null) return; // Ya redirigió a login

                // 2. VERIFICAR EDIFICIO SELECCIONADO
                if (!await VerificarEdificioSeleccionado(currentUser)) return; // Ya redirigió a select-building

                // 3. CARGAR DATOS DE LA PÁGINA
                await CargarDatosPagina();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"❌ Error en OnInitializedAsync: {ex.Message}");
            }
            finally
            {
                _isLoading = false;
            }
        }

        private async Task<UserSession> VerificarUsuarioAutenticado()
        {
            UserSession? currentUser = null;
            int intentos = 0;
            const int maxIntentos = 5;

            while (currentUser == null && intentos < maxIntentos)
            {
                currentUser = await AuthService.GetCurrentUserAsync();

                if (currentUser == null)
                {
                    intentos++;
                    Console.WriteLine($"⚠️ Intento {intentos}/{maxIntentos} - Usuario no autenticado, esperando 500ms...");
                    await Task.Delay(500);
                }
                else
                {
                    Console.WriteLine($"✅ Usuario encontrado: {currentUser.Email}");
                    return currentUser;
                }
            }

            Console.WriteLine($"❌ Usuario no autenticado después de {maxIntentos} intentos - Redirigiendo a login");
            Navigation.NavigateTo("/login", true);
            return null;
        }

        private async Task<bool> VerificarEdificioSeleccionado(UserSession currentUser)
        {
            if (currentUser.CurrentBuildingId == Guid.Empty)
            {
                Console.WriteLine("⚠️ No hay edificio seleccionado - Redirigiendo a select-building");
                Navigation.NavigateTo("/select-building", true);
                return false;
            }

            IdBuilding = currentUser.CurrentBuildingId;
            Console.WriteLine($"🏢 Edificio seleccionado: {IdBuilding}");
            return true;
        }

        private async Task CargarDatosPagina()
        {
            Console.WriteLine($"📦 Cargando datos para edificio: {IdBuilding}");

            // Cargar edificios del propietario
            Buildings = currentUser!.Buildings!.Select(ub => ub.Building).ToList()!;

            // Cargar parámetros
            filteredParameters = ParameterService.ListParameters;

            // Cargar categorías
            filteredCategory = await CategoryService.GetCategoriesAsync(IdBuilding);

            // Cargar unidades
            filteredUnits = await BuildingService.GetGroupUnitsByTypeAsync(IdBuilding, 1);

            // Cargar métodos de pago (PARAMETRO_PADRE = 16)
            _paymentMethods = filteredParameters
                .Where(c => c.IdParent == 16)
                .Select(c => c.ShortDescription)
                .ToList();

            // Seleccionar el primer edificio por defecto
            if (Buildings.Any())
            {
                SelectedBuilding = Buildings.First();   //GetBuildingDefault
                SelectedBuilding.Configuration = await GetConfigurationAsync(currentUser!.CurrentBuildingId);
            }

            Console.WriteLine("✅ Datos cargados correctamente");
        }

        private async Task<BuildingConfiguration> GetConfigurationAsync(Guid IdBuilding)
        {
            return await BuildingService.GetConfigurationAsync(IdBuilding);
        }

        private void SelectBuilding(Building building)
        {
            SelectedBuilding = building;
            CancelEdit(); // Cancelar cualquier edición en curso
        }

        private async Task EditBuilding(Building building)
        {
            _editingBuilding = building.Clone();
            _isEditingBuilding = true;
            await _buildingModal.ShowAsync();
        }

        private async Task ShowCreateModal()
        {
            _editingBuilding = new Building
            {
                IdBuilding = Guid.NewGuid(),
                Number = Buildings.Count + 1,
                IsActive = true,
                Configuration = BuildingService.CreateDefaultConfigurationAsync(Guid.NewGuid())
            };
            _isEditingBuilding = false;
            await _buildingModal.ShowAsync();
        }

        private async Task CloseBankModal()
        {
            //RemoveBankAccount(SelectedBuilding!.Configuration.BankAccounts.Count);
            await _bankAccount.HideAsync();
        }

        private async Task CloseContactModal()
        {
            RemoveBankAccount(SelectedBuilding!.Configuration.BankAccounts.Count);
            await _bankAccount.HideAsync();
        }

        private async Task CloseExonerationModal()
        {
            //RemoveBankAccount(SelectedBuilding!.Configuration.BankAccounts.Count);
            await _exoneration.HideAsync();
        }

        private async Task SaveBuilding()
        {
            try
            {
                if (_isEditingBuilding)
                {
                    var index = Buildings.FindIndex(b => b.IdBuilding == _editingBuilding.IdBuilding);
                    if (index >= 0)
                    {
                        Buildings[index] = _editingBuilding.Clone();
                    }
                }
                else
                {
                    Buildings.Add(_editingBuilding.Clone());
                }

                // Si estamos editando el edificio seleccionado, actualizarlo
                if (SelectedBuilding?.IdBuilding == _editingBuilding.IdBuilding)
                {
                    SelectedBuilding = _editingBuilding.Clone();
                }

                await _buildingModal.HideAsync();
                StateHasChanged();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error al guardar edificio: {ex.Message}");
            }
        }

        private async Task SaveBankAccout()
        {
            try
            {
                if (!_isEditingBanckAccount)
                {
                    SelectedBuilding!.Configuration.BankAccounts.Add(_editingBankAccout);
                    _editingBankAccout = new BankAccount();
                }
                else
                {
                    //SelectedBuilding!.Configuration.BankAccounts.Add(_editingBankAccout);
                }
                await _bankAccount.HideAsync();
                StateHasChanged();
                _isEditingBanckAccount = false;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error al guardar edificio: {ex.Message}");
            }
        }

        private async Task SaveContact()
        {
            try
            {
                if (!_isEditingBanckAccount)
                {
                    SelectedBuilding!.Configuration.BankAccounts.Add(_editingBankAccout);
                    _editingBankAccout = new BankAccount();
                }
                else
                {
                    //SelectedBuilding!.Configuration.BankAccounts.Add(_editingBankAccout);
                }
                await _bankAccount.HideAsync();
                StateHasChanged();
                _isEditingBanckAccount = false;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error al guardar edificio: {ex.Message}");
            }
        }

        private async Task SaveExoneration()
        {
            try
            {
                SelectedBuilding!.Configuration.Exonerations.Add(_Exoneration);
                _Exoneration = new Exoneration();
                await _exoneration.HideAsync();
                StateHasChanged();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error al guardar edificio: {ex.Message}");
            }
        }

        private void StartEditSection(string section)
        {
            if (SelectedBuilding != null)
            {
                _configurationBackup = SelectedBuilding.Configuration.Clone();
                _editingSection = section;
            }
        }

        private void CancelEdit()
        {
            if (SelectedBuilding != null && !string.IsNullOrEmpty(_editingSection))
            {
                SelectedBuilding.Configuration = _configurationBackup.Clone();
            }
            _editingSection = "";
        }

        private async Task SaveSection(string section)
        {
            try
            {
                // Aquí iría la lógica para guardar en la base de datos
                var interno = SelectedBuilding!.Configuration;

                //validar el Id, si esta vacio, guardar configuracion Base
                if (interno.IdBuildingConfiguration == Guid.Empty)
                {
                    interno.IdBuildingConfiguration = Guid.NewGuid();
                    interno.IdBuilding = currentUser.CurrentBuildingId;
                    await BuildingService.CreateConfigurationAsync(interno);
                }

                switch (section)
                {
                    case "payments":
                        //await SaveSectionAAsync(ct);

                        break;

                    case "currency":
                        //await SaveSectionBAsync(ct);
                        //Actualizar Moneda

                        //Actualizar Bank Account
                        if (interno.BankAccounts.Count > 0)
                        {
                            foreach (var bankaccount in interno.BankAccounts)
                            {
                                if (bankaccount.IdBankAccount == Guid.Empty)
                                {
                                    //add BankAccount

                                    // Busca el primer elemento que cumpla las condiciones
                                    //<!--    PARAMETRO_PADRE     -->
                                    var match = filteredParameters!
                                        .FirstOrDefault(c => c.IdParent == 31 && c.Value == bankaccount.AccountType);

                                    // Asigna el nombre si se encontró coincidencia, de lo contrario usa un valor por defecto
                                    bankaccount.AccountName = match?.ShortDescription ?? "Nombre no disponible";

                                    bankaccount.IdBankAccount = Guid.NewGuid();
                                    bankaccount.IdBuilding = interno.IdBuilding;

                                    await BankAccountService.AddBankAccount(bankaccount);
                                }
                                else
                                {
                                    //Update BankAccount
                                    await BankAccountService.UpdateBankAccount(bankaccount);
                                }
                            }
                        }
                        break;

                    case "fines":
                        //await SaveSectionCAsync(ct);
                        break;
                    case "admin":
                        //await SaveSectionAAsync(ct);

                        if (SelectedBuilding.Configuration.AdminContact.IdContact == Guid.Empty)
                        {
                            SelectedBuilding.Configuration.AdminContact.IdContact = Guid.NewGuid();
                            SelectedBuilding.Configuration.AdminContact.IdRelatedEntity = interno.IdBuildingConfiguration;
                            SelectedBuilding.Configuration.AdminContact.TypeContact = 1;
                            await BuildingService.AddContactAsync(SelectedBuilding.Configuration.AdminContact);
                        }
                        else
                        {
                            await BuildingService.UpdateContactAsync(SelectedBuilding.Configuration.AdminContact);
                        }
                        break;

                    case "realty":
                        //await SaveSectionBAsync(ct);
                        if (SelectedBuilding.Configuration.RealEstateCompany.IdContact == Guid.Empty)
                        {
                            SelectedBuilding.Configuration.RealEstateCompany.IdContact = Guid.NewGuid();
                            SelectedBuilding.Configuration.RealEstateCompany.IdRelatedEntity = interno.IdBuildingConfiguration;
                            SelectedBuilding.Configuration.RealEstateCompany.TypeContact = 2;
                            await BuildingService.AddContactAsync(SelectedBuilding.Configuration.RealEstateCompany);
                        }
                        else
                        {
                            await BuildingService.UpdateContactAsync(SelectedBuilding.Configuration.RealEstateCompany);
                        }
                        break;

                    case "maintenance":
                        //await SaveSectionCAsync(ct);
                        if (SelectedBuilding.Configuration.MaintenanceCompany.IdContact == Guid.Empty)
                        {
                            SelectedBuilding.Configuration.MaintenanceCompany.IdContact = Guid.NewGuid();
                            SelectedBuilding.Configuration.MaintenanceCompany.IdRelatedEntity = interno.IdBuildingConfiguration;
                            SelectedBuilding.Configuration.MaintenanceCompany.TypeContact = 3;
                            await BuildingService.AddContactAsync(SelectedBuilding.Configuration.MaintenanceCompany);
                        }
                        else
                        {
                            await BuildingService.UpdateContactAsync(SelectedBuilding.Configuration.MaintenanceCompany);
                        }
                        break;
                    case "category":
                        //await SaveSectionCAsync(ct);
                        break;
                    case "exception":
                        //Actualizar Bank Account
                        if (interno.Exonerations.Count > 0)
                        {
                            foreach (var _exception in interno.Exonerations)
                            {
                                if (_exception.IdExoneration == Guid.Empty)
                                {
                                    //add Exoneration
                                    _exception.IdExoneration = Guid.NewGuid();
                                    _exception.IdBuilding = interno.IdBuilding;

                                    await BuildingService.AddExonerationAsync(_exception);
                                }
                                else
                                {
                                    //Delete Exoneration
                                    if (_exception.IsDeleted)
                                        await BuildingService.DeleteExonerationAsync(_exception);
                                }
                            }
                        }
                        break;
                    default:
                        //await SaveSectionDefaultAsync(section, ct);
                        break;
                }

                await BuildingService.UpdateConfigurationAsync(SelectedBuilding.Configuration);

                _editingSection = "";
                StateHasChanged();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error al guardar: {ex.Message}");
            }
        }

        private async Task SaveConfiguration()
        {
            try
            {
                // Guardar todas las configuraciones del edificio actual
                await Task.Delay(500);
                // Lógica de guardado en base de datos
                // await SaveBuildingConfiguration(SelectedBuilding);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error al guardar configuración: {ex.Message}");
            }
        }

        private async Task SaveAllConfigurations()
        {
            try
            {
                // Guardar configuraciones de todos los edificios
                // Esta función sería útil para guardar cambios en lote
                foreach (var building in Buildings)
                {
                    //await SaveBuildingConfiguration(building);
                }

                // Mostrar mensaje de éxito
                Console.WriteLine("Todas las configuraciones guardadas exitosamente");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error al guardar todas las configuraciones: {ex.Message}");
            }
        }

        private void AddBankAccount()
        {
            if (SelectedBuilding != null)
            {
                //SelectedBuilding.Configuration.BankAccounts.Add(new BankAccount());
                _bankAccount.ShowAsync();
            }
        }

        private void ShowAddExceptionModal()
        {
            if (SelectedBuilding != null)
            {
                _exoneration.ShowAsync();
            }
        }

        private void EditBankAccount(int index)
        {
            if (SelectedBuilding != null && SelectedBuilding.Configuration.BankAccounts.Count > 1)
            {
                _editingBankAccout = SelectedBuilding.Configuration.BankAccounts[index];
                _isEditingBanckAccount = true;
            }
            _bankAccount.ShowAsync();
        }

        private void RemoveBankAccount(int index)
        {
            if (SelectedBuilding != null && SelectedBuilding.Configuration.BankAccounts.Count > 1)
            {
                SelectedBuilding.Configuration.BankAccounts.RemoveAt(index);
            }
        }

        private void RemoveException(Exoneration item)
        {
            item.IsDeleted = true;
            StateHasChanged();
        }

        private void TogglePaymentMethod(string method)
        {
            if (SelectedBuilding != null)
            {
                if (SelectedBuilding.Configuration.PaymentMethods.Contains(method))
                {
                    SelectedBuilding.Configuration.PaymentMethods.Remove(method);
                }
                else
                {
                    SelectedBuilding.Configuration.PaymentMethods.Add(method);
                }
            }
        }

        private async Task ShowQuickConfig(Building building)
        {
            _quickConfigBuilding = building;
            _sourceBuildingId = null;
            _copyCurrency = _copyPayments = _copyFines = _copyContacts = _copyAll = true;
            await _quickConfigModal.ShowAsync();
        }

        private async Task ApplyQuickConfig()
        {
            if (_quickConfigBuilding != null && _sourceBuildingId.HasValue)
            {
                var sourceBuilding = Buildings.FirstOrDefault(b => b.IdBuilding == _sourceBuildingId.Value);
                if (sourceBuilding != null)
                {
                    if (_copyCurrency)
                    {
                        _quickConfigBuilding.Configuration.Currency = sourceBuilding.Configuration.Currency;
                        _quickConfigBuilding.Configuration.BankAccounts = sourceBuilding.Configuration.BankAccounts
                            .Select(a => a.Clone()).ToList();
                    }

                    if (_copyPayments)
                    {
                        _quickConfigBuilding.Configuration.PaymentMethods = new List<string>(sourceBuilding.Configuration.PaymentMethods);
                        _quickConfigBuilding.Configuration.PaymentPeriod = sourceBuilding.Configuration.PaymentPeriod;
                        _quickConfigBuilding.Configuration.DueDay = sourceBuilding.Configuration.DueDay;
                    }

                    if (_copyFines)
                    {
                        _quickConfigBuilding.Configuration.FineAmount = sourceBuilding.Configuration.FineAmount;
                        _quickConfigBuilding.Configuration.LateInterestRate = sourceBuilding.Configuration.LateInterestRate;
                        _quickConfigBuilding.Configuration.InvoiceDay = sourceBuilding.Configuration.InvoiceDay;
                    }

                    if (_copyContacts)
                    {
                        _quickConfigBuilding.Configuration.AdminContact = sourceBuilding.Configuration.AdminContact.Clone();
                        _quickConfigBuilding.Configuration.RealEstateCompany = sourceBuilding.Configuration.RealEstateCompany.Clone();
                        _quickConfigBuilding.Configuration.MaintenanceCompany = sourceBuilding.Configuration.MaintenanceCompany.Clone();
                    }

                    // Si estamos editando el edificio seleccionado, actualizar la vista
                    if (SelectedBuilding?.IdBuilding == _quickConfigBuilding.IdBuilding)
                    {
                        SelectedBuilding = _quickConfigBuilding;
                    }

                    await _quickConfigModal.HideAsync();
                    StateHasChanged();
                }
            }
        }

        private async Task CopyConfigToAll()
        {
            if (SelectedBuilding != null)
            {
                // Copiar configuración del edificio seleccionado a todos los demás
                foreach (var building in Buildings.Where(b => b.IdBuilding != SelectedBuilding.IdBuilding))
                {
                    building.Configuration = SelectedBuilding.Configuration.Clone();
                }

                // Mostrar mensaje de éxito
                Console.WriteLine($"Configuración copiada a {Buildings.Count - 1} edificios");
            }
        }

        private bool CopyAll
        {
            get => _copyAll;
            set
            {
                _copyAll = value;
                if (value)
                {
                    _copyCurrency = _copyPayments = _copyFines = _copyContacts = true;
                }
                else
                {
                    _copyCurrency = _copyPayments = _copyFines = _copyContacts = false;
                }
            }
        }

        private async Task ChangeTypeAccount(ChangeEventArgs args)
        {
            //Logica para cambiar el tipo de cuenta
            _editingBankAccout.AccountNumber = args.Value!.ToString()!;
        }

        private string GetCategoryName(Guid IdSearch)
        {
            var category = filteredCategory.FirstOrDefault(c => c.IdCategory == IdSearch);
            return category?.ShortDescript ?? "Categoría General";
        }

        private string GetGroupUnitName(Guid IdSearch)
        {
            var groupunit = filteredUnits.FirstOrDefault(c => c.IdGroupUnit == IdSearch);
            return groupunit?.UnitNumber ?? "Sin Data";
        }

    }
}