// <autogenerated />
#nullable enable
using BlazorBootstrap;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Forms;
using SpiderHood.Components.Pages.Components;
using SpiderHood.Models;
using SpiderHood.Utilities;

namespace SpiderHood.Components.Pages.ReservationPages
{
    public partial class ReservationsAdmin
    {
        private bool _loading = true;
        private bool _canGestionar;
        private bool _canAprobar;
        private UserSession currentUser = new();
        private List<UnitView> _unidades = new();
        private List<CommonArea> _areasComunes = new();

        private ReservationPagination _pagination = new();
        private string _searchTerm = string.Empty;

        private string? _resultado;
        private bool _resultadoOk;
        private bool _procesando;

        // Distinto de _resultado -- ese alert vive en el cuerpo de la página y queda
        // tapado por el backdrop del Modal mientras está abierto (feedback del usuario
        // 2026-09-12: "el mensaje sale por atrás, no se ve"). Los errores de validación
        // que ocurren CON el modal todavía abierto se muestran acá adentro en su lugar --
        // compartido entre los modales de esta página porque sólo uno está abierto a la vez.
        private string? _errorModal;

        private Modal _checklistModal = null!;
        private Modal _cerrarModal = null!;
        private Reservation? _reservaSeleccionada;
        private ChecklistStage _etapaChecklist = ChecklistStage.Entrega;
        private List<ReservationChecklistItem> _checklistItems = new();
        private string _nuevoItemDescripcion = string.Empty;
        private ChecklistStatus _nuevoItemEstado = ChecklistStatus.Ok;
        private string _nuevoItemObservacion = string.Empty;
        private List<StagedFoto> _fotosStaged = new();
        private decimal _montoDanio;

        private Modal _confirmarPagoModal = null!;
        private decimal _montoPagoConfirmado;
        private DateTime _fechaPagoConfirmado = DateTime.Today;

        private ConfirmationModal? _confirmationModal;
        private RejectionModal? _rejectionModal;

        private Modal _nuevaReservationModal = null!;
        private CommonArea? _areaSeleccionada;
        private List<Reservation> _proximasReservations = new();
        private Reservation _nuevaReservation = new();

        private record StagedFoto(string FileName, string ContentType, byte[] Content);

        private string Moneda(decimal valor) => valor.FormatoMoneda(ParameterService.CurrentBuilding?.Configuration.Currency);

        protected override async Task OnInitializedAsync()
        {
            currentUser = await AuthService.GetCurrentUserAsync() ?? new UserSession();
            _canGestionar = await PermissionService.HasPermissionAsync(currentUser, "manage_reservations");
            _canAprobar = await PermissionService.HasPermissionAsync(currentUser, "approve_reservations");

            if ((_canGestionar || _canAprobar) && currentUser.CurrentBuildingId != Guid.Empty)
            {
                if (ParameterService.CurrentBuilding == null || ParameterService.CurrentBuilding.IdBuilding != currentUser.CurrentBuildingId)
                {
                    await ParameterService.LoadParametersAsync(currentUser.CurrentBuildingId);
                }

                // Una unidad sin propietario/grupo asignado (IdGroupUnit null) no puede ser
                // "responsable" de una reserva -- no hay a quién asociársela -- así que no
                // entra al desplegable.
                _unidades = (await BuildingService.GetGroupUnitsByTypeAsync(currentUser.CurrentBuildingId, 1))
                    .Where(u => u.IdGroupUnit.HasValue)
                    .ToList();
                _areasComunes = (await CommonAreaService.GetCommonAreasAsync(currentUser.CurrentBuildingId))
                    .Where(a => a.Activo)
                    .ToList();
                await CargarReservationsAsync();
            }

            _loading = false;
        }

        private async Task CargarReservationsAsync()
        {
            var reservas = await ReservationService.GetReservationsAsync(currentUser.CurrentBuildingId);
            _pagination.Initialize(reservas);
        }

        private void OnSearch(ChangeEventArgs e)
        {
            _searchTerm = e.Value?.ToString() ?? string.Empty;
            _pagination.Search(_searchTerm);
        }

        private string GetGroupUnitName(Guid idGroupUnit)
            => _unidades.FirstOrDefault(u => u.IdGroupUnit == idGroupUnit)?.UnitNumber is { } numero ? $"DPTO {numero}" : "Sin Data";

        private void LimpiarChecklist()
        {
            _checklistItems = new();
            _fotosStaged = new();
            _nuevoItemDescripcion = string.Empty;
            _nuevoItemEstado = ChecklistStatus.Ok;
            _nuevoItemObservacion = string.Empty;
            _errorModal = null;
        }

        private async Task AbrirCheckIn(Reservation reserva)
        {
            _reservaSeleccionada = reserva;
            _etapaChecklist = ChecklistStage.Entrega;
            LimpiarChecklist();
            await _checklistModal.ShowAsync();
        }

        private async Task AbrirCheckOut(Reservation reserva)
        {
            _reservaSeleccionada = reserva;
            _etapaChecklist = ChecklistStage.Devolucion;
            LimpiarChecklist();
            await _checklistModal.ShowAsync();
        }

        private async Task AbrirCerrar(Reservation reserva)
        {
            _reservaSeleccionada = reserva;
            _montoDanio = 0;
            _errorModal = null;
            await _cerrarModal.ShowAsync();
        }

        private async Task AbrirConfirmarPago(Reservation reserva)
        {
            _reservaSeleccionada = reserva;
            _montoPagoConfirmado = reserva.MontoGarantia + reserva.MontoAlquiler + reserva.MontoLimpieza;
            _fechaPagoConfirmado = DateTime.Today;
            _errorModal = null;
            await _confirmarPagoModal.ShowAsync();
        }

        private async Task ConfirmarPago()
        {
            if (_reservaSeleccionada == null) return;

            _procesando = true;
            StateHasChanged();

            try
            {
                await ReservationService.ConfirmarPagoAsync(_reservaSeleccionada.IdReservation, _montoPagoConfirmado, _fechaPagoConfirmado, currentUser.IdUser);
                _resultadoOk = true;
                _resultado = "Pago confirmado.";
                await _confirmarPagoModal.HideAsync();
                await CargarReservationsAsync();
            }
            finally
            {
                _procesando = false;
                StateHasChanged();
            }
        }

        private void AgregarItemChecklist()
        {
            if (string.IsNullOrWhiteSpace(_nuevoItemDescripcion)) return;

            _checklistItems.Add(new ReservationChecklistItem
            {
                Descripcion = _nuevoItemDescripcion,
                Estado = _nuevoItemEstado,
                Observacion = string.IsNullOrWhiteSpace(_nuevoItemObservacion) ? null : _nuevoItemObservacion
            });

            _nuevoItemDescripcion = string.Empty;
            _nuevoItemEstado = ChecklistStatus.Ok;
            _nuevoItemObservacion = string.Empty;
        }

        private async Task SeleccionarFotos(InputFileChangeEventArgs e)
        {
            foreach (var file in e.GetMultipleFiles(maximumFileCount: 10))
            {
                try
                {
                    using var stream = file.OpenReadStream(maxAllowedSize: 50 * 1024 * 1024);
                    using var memoryStream = new MemoryStream();
                    await stream.CopyToAsync(memoryStream);
                    _fotosStaged.Add(new StagedFoto(file.Name, file.ContentType, memoryStream.ToArray()));
                }
                catch (Exception ex)
                {
                    _resultado = $"No se pudo leer \"{file.Name}\": {ex.Message}";
                    _resultadoOk = false;
                }
            }
        }

        private async Task ConfirmarChecklist()
        {
            if (_reservaSeleccionada == null) return;

            _procesando = true;
            StateHasChanged();

            try
            {
                var checklist = _checklistItems
                    .Select(i => (i.Descripcion, i.Estado, i.Observacion))
                    .ToList();
                var fotos = _fotosStaged
                    .Select(f => (f.Content, f.FileName, f.ContentType))
                    .ToList();

                if (_etapaChecklist == ChecklistStage.Entrega)
                {
                    var resultado = await ReservationService.HacerCheckInAsync(_reservaSeleccionada.IdReservation, currentUser.IdUser, checklist, fotos);
                    if (!resultado.Exito)
                    {
                        _errorModal = resultado.Mensaje;
                        return;
                    }
                    _resultadoOk = true;
                    _resultado = resultado.Mensaje;
                }
                else
                {
                    await ReservationService.HacerCheckOutAsync(_reservaSeleccionada.IdReservation, currentUser.IdUser, checklist, fotos);
                    _resultadoOk = true;
                    _resultado = "Check-out registrado.";
                }

                await _checklistModal.HideAsync();
                await CargarReservationsAsync();
            }
            finally
            {
                _procesando = false;
                StateHasChanged();
            }
        }

        private async Task ConfirmarCerrar()
        {
            if (_reservaSeleccionada == null) return;

            _procesando = true;
            StateHasChanged();

            try
            {
                var resultado = await ReservationService.CerrarAsync(_reservaSeleccionada.IdReservation, currentUser.IdUser, _montoDanio);

                if (resultado.Exito)
                {
                    _resultadoOk = true;
                    _resultado = $"Reserva cerrada -- Devuelto: {Moneda(resultado.MontoDevuelto)}, Retenido: {Moneda(resultado.MontoRetenido)}" +
                        (resultado.SeGeneroCuotaExtraordinaria ? $", Cuota Extraordinaria generada por {Moneda(resultado.MontoCuotaExtraordinaria)}." : ".");
                    await _cerrarModal.HideAsync();
                    await CargarReservationsAsync();
                }
                else
                {
                    _errorModal = resultado.Mensaje;
                }
            }
            finally
            {
                _procesando = false;
                StateHasChanged();
            }
        }

        private void PedirAprobar(Reservation reserva)
        {
            if (!_canAprobar || _confirmationModal == null) return;
            _reservaSeleccionada = reserva;
            _confirmationModal.Title = "Aprobar Reserva";
            _confirmationModal.Message = $"¿Aprobar la reserva de {reserva.NombreCommonArea} del {reserva.FechaInicio:dd/MM/yyyy HH:mm}?";
            _confirmationModal.ConfirmText = "Aprobar";
            _confirmationModal.Show("info");
        }

        private async Task OnAprobarConfirmado(bool confirmado)
        {
            var reserva = _reservaSeleccionada;
            _reservaSeleccionada = null;
            if (!confirmado || reserva == null || !_canAprobar) return;

            await ReservationService.AprobarAsync(reserva.IdReservation, currentUser.IdUser);
            await CargarReservationsAsync();
        }

        private void PedirRechazar(Reservation reserva)
        {
            if (!_canAprobar || _rejectionModal == null) return;
            _reservaSeleccionada = reserva;
            _rejectionModal.Show();
        }

        private async Task OnRechazarConfirmado(string? motivo)
        {
            var reserva = _reservaSeleccionada;
            _reservaSeleccionada = null;
            if (motivo == null || reserva == null || !_canAprobar) return; // cancelado

            await ReservationService.RechazarAsync(reserva.IdReservation, currentUser.IdUser, motivo);
            await CargarReservationsAsync();
        }

        private async Task SincronizarCalendario(Reservation reserva)
        {
            var creado = await ReservationService.AsegurarCalendarItemAsync(reserva.IdReservation);
            _resultadoOk = creado;
            _resultado = creado
                ? "Reserva sincronizada -- ya debería verse en el Calendario."
                : "Esta reserva ya estaba sincronizada o su estado ya no lo necesita.";
            await CargarReservationsAsync();
        }

        private async Task AbrirNuevaReservation()
        {
            _resultado = null;
            _errorModal = null;
            _areaSeleccionada = _areasComunes.FirstOrDefault();
            _nuevaReservation = new Reservation
            {
                IdBuilding = currentUser.CurrentBuildingId,
                CreatedBy = currentUser.IdUser,
                FechaInicio = DateTime.Today.AddDays(1).AddHours(18),
                FechaFin = DateTime.Today.AddDays(1).AddHours(22)
            };

            if (_areaSeleccionada != null)
            {
                _proximasReservations = await ReservationService.GetProximasAsync(_areaSeleccionada.IdCommonArea);
            }

            await _nuevaReservationModal.ShowAsync();
        }

        private async Task OnAreaChanged(ChangeEventArgs e)
        {
            if (Guid.TryParse(e.Value?.ToString(), out var idCommonArea))
            {
                _areaSeleccionada = _areasComunes.FirstOrDefault(a => a.IdCommonArea == idCommonArea);
                _proximasReservations = _areaSeleccionada != null
                    ? await ReservationService.GetProximasAsync(_areaSeleccionada.IdCommonArea)
                    : new List<Reservation>();
            }
        }

        private async Task ConfirmarNuevaReservation()
        {
            if (_areaSeleccionada == null || _nuevaReservation.IdGroupUnit == Guid.Empty) return;

            _procesando = true;
            StateHasChanged();

            try
            {
                var resultado = await ReservationService.SolicitarAsync(_nuevaReservation, _areaSeleccionada);

                if (resultado.Exito)
                {
                    _resultadoOk = true;
                    _resultado = resultado.Mensaje;
                    await _nuevaReservationModal.HideAsync();
                    await CargarReservationsAsync();
                }
                else
                {
                    _errorModal = resultado.Mensaje;
                }
            }
            finally
            {
                _procesando = false;
                StateHasChanged();
            }
        }

        private static string EtiquetaEstado(Reservation reserva) => reserva.Estado switch
        {
            ReservationStatus.PendienteDeAprobacion => "🕒 Pendiente de Aprobación",
            ReservationStatus.Aprobada => "✅ Aprobada",
            ReservationStatus.Rechazada => "❌ Rechazada",
            ReservationStatus.Cancelada => "🚫 Cancelada",
            ReservationStatus.NoPresentado => "⚠️ No Presentado",
            ReservationStatus.Entregada => "🔑 Entregada",
            ReservationStatus.Finalizada => "🏁 Finalizada",
            ReservationStatus.Cerrada => "🔒 Cerrada",
            _ => reserva.Estado.ToString()
        };

        private static string EtiquetaChecklistStatus(ChecklistStatus estado) => estado switch
        {
            ChecklistStatus.Ok => "OK",
            ChecklistStatus.Danado => "Dañado",
            ChecklistStatus.Falta => "Falta",
            _ => estado.ToString()
        };
    }
}
