// <autogenerated />
#nullable enable
using BlazorBootstrap;
using Microsoft.AspNetCore.Components;
using SpiderHood.Components.Pages.Components;
using SpiderHood.Models;
using SpiderHood.Utilities;

namespace SpiderHood.Components.Pages.ReservationPages
{
    public partial class Reservations
    {
        private bool _loading = true;
        private UserSession currentUser = new();
        private Guid? _idGroupUnit;

        private List<CommonArea> _areasComunes = new();
        private CommonArea? _areaSeleccionada;
        private List<Reservation> _proximasReservations = new();

        private ReservationPagination _pagination = new();
        private string _searchTerm = string.Empty;

        private Reservation _form = new();
        private bool _solicitando;
        private string? _resultado;
        private bool _resultadoOk;

        // Distinto de _resultado -- ese alert vive en el cuerpo de la página y queda
        // tapado por el backdrop del Modal mientras está abierto (feedback del usuario
        // 2026-09-12: "el mensaje sale por atrás, no se ve"). Los errores de validación
        // que ocurren CON el modal todavía abierto (ej. "el área ya está reservada en
        // ese horario") se muestran acá adentro en su lugar.
        private string? _errorModal;

        private Modal _nuevaModal = null!;
        private ConfirmationModal? _confirmationModal;
        private readonly ConfirmationUtil _util = new();
        private Reservation? _reservaACancelar;

        private Modal _detalleModal = null!;
        private Reservation? _reservaDetalle;
        private List<ReservationChecklistItem> _checklistDetalle = new();
        private List<ReservationAttachment> _adjuntosDetalle = new();

        private Modal _reprogramarModal = null!;
        private Reservation? _reservaAReprogramar;
        private DateTime _nuevaFechaInicio;
        private DateTime _nuevaFechaFin;
        private bool _reprogramando;
        private string? _errorReprogramar;

        private string Moneda(decimal valor) => valor.FormatoMoneda(ParameterService.CurrentBuilding?.Configuration.Currency);

        protected override async Task OnInitializedAsync()
        {
            currentUser = await AuthService.GetCurrentUserAsync() ?? new UserSession();
            _idGroupUnit = await AuthService.GetCurrentUnitIdAsync();

            // Esta pantalla es de autoservicio del Residente (siempre reserva a nombre de
            // SU unidad) -- Administrador/Junta/SysAdmin nunca tienen una acá, así que
            // "sin unidad" no es un caso de error para ellos sino la señal de que vinieron
            // a la pantalla equivocada. Si tiene el permiso de gestión, se lo manda directo
            // a /reservas-admin (ahí puede elegir cualquier unidad como responsable) en vez
            // de dejarlo en un cartel de advertencia -- feedback del usuario (2026-09-12):
            // seguía sin poder entrar, no encontraba el otro link.
            if (_idGroupUnit == null && currentUser.CurrentBuildingId != Guid.Empty
                && await PermissionService.HasPermissionAsync(currentUser, "manage_reservations"))
            {
                Navigation.NavigateTo("/reservations-admin");
                return;
            }

            if (currentUser.CurrentBuildingId != Guid.Empty && _idGroupUnit != null)
            {
                if (ParameterService.CurrentBuilding == null || ParameterService.CurrentBuilding.IdBuilding != currentUser.CurrentBuildingId)
                {
                    await ParameterService.LoadParametersAsync(currentUser.CurrentBuildingId);
                }

                _areasComunes = (await CommonAreaService.GetCommonAreasAsync(currentUser.CurrentBuildingId))
                    .Where(a => a.Activo)
                    .ToList();

                await CargarReservationsAsync();
            }

            _loading = false;
        }

        private async Task CargarReservationsAsync()
        {
            var reservas = await ReservationService.GetReservationsByGroupUnitAsync(_idGroupUnit!.Value);
            _pagination.Initialize(reservas);
        }

        private void OnSearch(ChangeEventArgs e)
        {
            _searchTerm = e.Value?.ToString() ?? string.Empty;
            _pagination.Search(_searchTerm);
        }

        private async Task AbrirNuevaSolicitud()
        {
            _resultado = null;
            _errorModal = null;
            _areaSeleccionada = _areasComunes.FirstOrDefault();
            _form = new Reservation
            {
                IdBuilding = currentUser.CurrentBuildingId,
                IdGroupUnit = _idGroupUnit!.Value,
                CreatedBy = currentUser.IdUser,
                FechaInicio = DateTime.Today.AddDays(1).AddHours(18),
                FechaFin = DateTime.Today.AddDays(1).AddHours(22)
            };

            if (_areaSeleccionada != null)
            {
                _proximasReservations = await ReservationService.GetProximasAsync(_areaSeleccionada.IdCommonArea);
            }

            await _nuevaModal.ShowAsync();
        }

        private async Task OnAreaChanged(ChangeEventArgs e)
        {
            if (Guid.TryParse(e.Value?.ToString(), out var idCommonArea))
            {
                _areaSeleccionada = _areasComunes.FirstOrDefault(a => a.IdCommonArea == idCommonArea);
                _proximasReservations = _areaSeleccionada != null
                    ? await ReservationService.GetProximasAsync(_areaSeleccionada.IdCommonArea)
                    : new List<Reservation>();
            }
        }

        private async Task ConfirmarSolicitar()
        {
            if (_areaSeleccionada == null) return;

            _solicitando = true;
            StateHasChanged();

            try
            {
                var resultado = await ReservationService.SolicitarAsync(_form, _areaSeleccionada);

                if (resultado.Exito)
                {
                    _resultadoOk = true;
                    _resultado = resultado.Mensaje;
                    await _nuevaModal.HideAsync();
                    await CargarReservationsAsync();
                }
                else
                {
                    // El modal sigue abierto -- el mensaje va adentro (_errorModal), no en
                    // _resultado (quedaría tapado por el backdrop del modal).
                    _errorModal = resultado.Mensaje;
                }
            }
            finally
            {
                _solicitando = false;
                StateHasChanged();
            }
        }

        private async Task VerDetalle(Reservation reserva)
        {
            _reservaDetalle = reserva;
            _checklistDetalle = await ReservationService.GetChecklistAsync(reserva.IdReservation);
            _adjuntosDetalle = await ReservationService.GetAdjuntosAsync(reserva.IdReservation);
            await _detalleModal.ShowAsync();
        }

        private async Task AbrirReprogramar(Reservation reserva)
        {
            _reservaAReprogramar = reserva;
            _nuevaFechaInicio = reserva.FechaInicio;
            _nuevaFechaFin = reserva.FechaFin;
            _errorReprogramar = null;
            await _reprogramarModal.ShowAsync();
        }

        private async Task ConfirmarReprogramar()
        {
            if (_reservaAReprogramar == null) return;

            var areaComun = _areasComunes.FirstOrDefault(a => a.IdCommonArea == _reservaAReprogramar.IdCommonArea);
            if (areaComun == null)
            {
                _errorReprogramar = "No se encontró la configuración del área común.";
                return;
            }

            _reprogramando = true;
            StateHasChanged();

            try
            {
                var resultado = await ReservationService.ReprogramarAsync(_reservaAReprogramar.IdReservation, _nuevaFechaInicio, _nuevaFechaFin, areaComun);
                if (resultado.Exito)
                {
                    _resultadoOk = true;
                    _resultado = resultado.Mensaje;
                    await _reprogramarModal.HideAsync();
                    await CargarReservationsAsync();
                }
                else
                {
                    _errorReprogramar = resultado.Mensaje;
                }
            }
            finally
            {
                _reprogramando = false;
                StateHasChanged();
            }
        }

        private void PedirCancelar(Reservation reserva)
        {
            if (_confirmationModal == null) return;
            _reservaACancelar = reserva;
            _confirmationModal.Title = "Cancelar Reserva";
            _confirmationModal.Message = $"¿Cancelar la reserva de {reserva.NombreCommonArea} del {reserva.FechaInicio:dd/MM/yyyy HH:mm}? " +
                "Según la configuración del área, esto puede retener la garantía si faltan pocos días para el evento.";
            _confirmationModal.ConfirmText = "Cancelar Reserva";
            _confirmationModal.Show("danger");
        }

        private async Task OnConfirmationResult(bool confirmado)
        {
            var reserva = _reservaACancelar;
            _reservaACancelar = null;
            if (!confirmado || reserva == null) return;

            var area = _areasComunes.FirstOrDefault(a => a.IdCommonArea == reserva.IdCommonArea)
                ?? (await CommonAreaService.GetCommonAreasAsync(currentUser.CurrentBuildingId)).First(a => a.IdCommonArea == reserva.IdCommonArea);

            await ReservationService.CancelarAsync(reserva.IdReservation, area);
            await CargarReservationsAsync();
        }

        private static string EtiquetaEstado(Reservation reserva) => reserva.Estado switch
        {
            ReservationStatus.PendienteDeAprobacion => "🕒 Pendiente de Aprobación",
            ReservationStatus.Aprobada => "✅ Aprobada",
            ReservationStatus.Rechazada => "❌ Rechazada",
            ReservationStatus.Cancelada => "🚫 Cancelada",
            ReservationStatus.NoPresentado => "⚠️ No Presentado",
            ReservationStatus.Entregada => "🔑 Entregada",
            ReservationStatus.Finalizada => "🏁 Finalizada",
            ReservationStatus.Cerrada => "🔒 Cerrada",
            _ => reserva.Estado.ToString()
        };
    }
}
