// <autogenerated />
#nullable enable
using BlazorBootstrap;
using Microsoft.AspNetCore.Components;
using SpiderHood.Components.Pages.Components;
using SpiderHood.Models;
using SpiderHood.Utilities;

namespace SpiderHood.Components.Pages.ReservationPages
{
    public partial class Reservas
    {
        private bool _loading = true;
        private UserSession currentUser = new();
        private Guid? _idGroupUnit;

        private List<AreaComun> _areasComunes = new();
        private AreaComun? _areaSeleccionada;
        private List<Reserva> _proximasReservas = new();

        private ReservaPagination _pagination = new();
        private string _searchTerm = string.Empty;

        private Reserva _form = new();
        private bool _solicitando;
        private string? _resultado;
        private bool _resultadoOk;

        // Distinto de _resultado -- ese alert vive en el cuerpo de la página y queda
        // tapado por el backdrop del Modal mientras está abierto (feedback del usuario
        // 2026-09-12: "el mensaje sale por atrás, no se ve"). Los errores de validación
        // que ocurren CON el modal todavía abierto (ej. "el área ya está reservada en
        // ese horario") se muestran acá adentro en su lugar.
        private string? _errorModal;

        private Modal _nuevaModal = null!;
        private ConfirmationModal? _confirmationModal;
        private readonly ConfirmationUtil _util = new();
        private Reserva? _reservaACancelar;

        private string Moneda(decimal valor) => valor.FormatoMoneda(ParameterService.CurrentBuilding?.Configuration.Currency);

        protected override async Task OnInitializedAsync()
        {
            currentUser = await AuthService.GetCurrentUserAsync() ?? new UserSession();
            _idGroupUnit = await AuthService.GetCurrentUnitIdAsync();

            if (currentUser.CurrentBuildingId != Guid.Empty && _idGroupUnit != null)
            {
                if (ParameterService.CurrentBuilding == null || ParameterService.CurrentBuilding.IdBuilding != currentUser.CurrentBuildingId)
                {
                    await ParameterService.LoadParametersAsync(currentUser.CurrentBuildingId);
                }

                _areasComunes = (await AreaComunService.GetAreaComunesAsync(currentUser.CurrentBuildingId))
                    .Where(a => a.Activo)
                    .ToList();

                await CargarReservasAsync();
            }

            _loading = false;
        }

        private async Task CargarReservasAsync()
        {
            var reservas = await ReservaService.GetReservasByGroupUnitAsync(_idGroupUnit!.Value);
            _pagination.Initialize(reservas);
        }

        private void OnSearch(ChangeEventArgs e)
        {
            _searchTerm = e.Value?.ToString() ?? string.Empty;
            _pagination.Search(_searchTerm);
        }

        private async Task AbrirNuevaSolicitud()
        {
            _resultado = null;
            _errorModal = null;
            _areaSeleccionada = _areasComunes.FirstOrDefault();
            _form = new Reserva
            {
                IdBuilding = currentUser.CurrentBuildingId,
                IdGroupUnit = _idGroupUnit!.Value,
                CreatedBy = currentUser.IdUser,
                FechaInicio = DateTime.Today.AddDays(1).AddHours(18),
                FechaFin = DateTime.Today.AddDays(1).AddHours(22)
            };

            if (_areaSeleccionada != null)
            {
                _proximasReservas = await ReservaService.GetProximasAsync(_areaSeleccionada.IdAreaComun);
            }

            await _nuevaModal.ShowAsync();
        }

        private async Task OnAreaChanged(ChangeEventArgs e)
        {
            if (Guid.TryParse(e.Value?.ToString(), out var idAreaComun))
            {
                _areaSeleccionada = _areasComunes.FirstOrDefault(a => a.IdAreaComun == idAreaComun);
                _proximasReservas = _areaSeleccionada != null
                    ? await ReservaService.GetProximasAsync(_areaSeleccionada.IdAreaComun)
                    : new List<Reserva>();
            }
        }

        private async Task ConfirmarSolicitar()
        {
            if (_areaSeleccionada == null) return;

            _solicitando = true;
            StateHasChanged();

            try
            {
                var resultado = await ReservaService.SolicitarAsync(_form, _areaSeleccionada);

                if (resultado.Exito)
                {
                    _resultadoOk = true;
                    _resultado = resultado.Mensaje;
                    await _nuevaModal.HideAsync();
                    await CargarReservasAsync();
                }
                else
                {
                    // El modal sigue abierto -- el mensaje va adentro (_errorModal), no en
                    // _resultado (quedaría tapado por el backdrop del modal).
                    _errorModal = resultado.Mensaje;
                }
            }
            finally
            {
                _solicitando = false;
                StateHasChanged();
            }
        }

        private void PedirCancelar(Reserva reserva)
        {
            if (_confirmationModal == null) return;
            _reservaACancelar = reserva;
            _confirmationModal.Title = "Cancelar Reserva";
            _confirmationModal.Message = $"¿Cancelar la reserva de {reserva.NombreAreaComun} del {reserva.FechaInicio:dd/MM/yyyy HH:mm}? " +
                "Según la configuración del área, esto puede retener la garantía si faltan pocos días para el evento.";
            _confirmationModal.ConfirmText = "Cancelar Reserva";
            _confirmationModal.Show("danger");
        }

        private async Task OnConfirmationResult(bool confirmado)
        {
            var reserva = _reservaACancelar;
            _reservaACancelar = null;
            if (!confirmado || reserva == null) return;

            var area = _areasComunes.FirstOrDefault(a => a.IdAreaComun == reserva.IdAreaComun)
                ?? (await AreaComunService.GetAreaComunesAsync(currentUser.CurrentBuildingId)).First(a => a.IdAreaComun == reserva.IdAreaComun);

            await ReservaService.CancelarAsync(reserva.IdReserva, area);
            await CargarReservasAsync();
        }

        private static string EtiquetaEstado(Reserva reserva) => reserva.Estado switch
        {
            ReservaEstado.PendienteDeAprobacion => "🕒 Pendiente de Aprobación",
            ReservaEstado.Aprobada => "✅ Aprobada",
            ReservaEstado.Rechazada => "❌ Rechazada",
            ReservaEstado.Cancelada => "🚫 Cancelada",
            ReservaEstado.NoPresentado => "⚠️ No Presentado",
            ReservaEstado.Entregada => "🔑 Entregada",
            ReservaEstado.Finalizada => "🏁 Finalizada",
            ReservaEstado.Cerrada => "🔒 Cerrada",
            _ => reserva.Estado.ToString()
        };
    }
}
